Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-06, with the labels that each got.

#390 Add ALB attributes annotation usage
  docs/ingress-resources.md
Labels: cncf-cla: yes

#394 Add OWNERS file
  MAINTAINERS
  OWNERS
Labels: cncf-cla: yes, size/XS

#397 Normalizing clusterName to lowercase
  pkg/controller/alb-controller.go
Labels: cncf-cla: yes, size/XS

#275 configurable target group attributes
  docs/ingress-resources.md
  pkg/alb/loadbalancer/loadbalancer.go
  pkg/alb/targetgroup/targetgroup.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/aws/elbv2/elbv2.go
  pkg/aws/elbv2/elbv2_test.go
Labels: cncf-cla: yes, size/L

#400 Align echoserver-ingress example with doc
  docs/walkthrough.md
  examples/echoservice/echoserver-ingress.yaml
Labels: cncf-cla: yes, size/M

#403 Fixing problems detected in TG attributes
  pkg/alb/listeners/listeners.go
  pkg/alb/loadbalancer/loadbalancer.go
  pkg/alb/rule/rule.go
  pkg/alb/targetgroup/targetgroup.go
  pkg/alb/targetgroups/targetgroups.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/aws/ec2/ec2.go
  pkg/aws/elbv2/elbv2.go
  pkg/controller/alb-controller.go
  pkg/util/log/log.go
  pkg/util/sync/sync.go
Labels: cncf-cla: yes, size/L

#404 Relocated to kubernetes-sigs
  .travis.yml
  BUILDING.md
  Makefile
  README.md
  ROADMAP.md
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  cmd/main.go
  docs/configuration.md
  docs/setup.md
  docs/walkthrough.md
  examples/alb-ingress-controller.yaml
  glide.yaml
  pkg/alb/listener/listener.go
  pkg/alb/listener/listener_test.go
  pkg/alb/listeners/listeners.go
  pkg/alb/listeners/listeners_test.go
  pkg/alb/loadbalancer/loadbalancer.go
  pkg/alb/loadbalancer/loadbalancer_test.go
  pkg/alb/rule/rule.go
  pkg/alb/rule/rule_test.go
  pkg/alb/rules/rules.go
  pkg/alb/rules/rules_test.go
  pkg/alb/targetgroup/targetgroup.go
  pkg/alb/targetgroups/targetgroups.go
  pkg/albingress/albingress.go
  pkg/albingress/albingress_test.go
  pkg/albingresses/albingresses.go
  pkg/annotations/annotations.go
  pkg/annotations/validation.go
  pkg/aws/ec2/ec2.go
  pkg/aws/elbv2/elbv2.go
  pkg/aws/elbv2/elbv2_test.go
  pkg/aws/session/session.go
  pkg/aws/waf/waf.go
  pkg/controller/alb-controller.go
  pkg/controller/alb-controller_test.go
  pkg/util/sync/sync.go
  pkg/util/types/types.go
  profile.cov
  test
Labels: cncf-cla: yes, size/XXL

#408 Update version to alpha.9 everywhere
  BUILDING.md
  README.md
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/XS

#409 Updating FOSSA badge location
  README.md
Labels: cncf-cla: yes, size/XS

#410 Nuked code coverage report, updated fossa url in readme, updated giti…
  .gitignore
  README.md
  profile.cov
Labels: cncf-cla: yes, size/XXL

#415 Support ALB SslPolicy via a new annotation
  docs/ingress-resources.md
  pkg/alb/listener/listener.go
  pkg/alb/listener/listener_test.go
  pkg/alb/listeners/listeners.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/annotations/validation.go
  pkg/annotations/validation_fake.go
Labels: cncf-cla: yes, size/M

#416 Fixed location of docker image
  .travis.yml
Labels: cncf-cla: yes, size/XS

#418 Use clusterName in annotation parser
  pkg/albingress/albingress_test.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/controller/alb-controller.go
Labels: cncf-cla: yes, size/S

#419 ocd log message correction
  pkg/util/sync/sync.go
Labels: size/XS

#420 Replaced successCodes annotation with success-codes, but kept support…
  docs/ingress-resources.md
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
Labels: cncf-cla: yes, size/M

#421 Normalized load balancer attributes annotation
  docs/ingress-resources.md
  pkg/alb/lb/loadbalancer.go
  pkg/alb/lb/loadbalancer_test.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
Labels: cncf-cla: yes, size/L

#423 Support for service level annotations
  docs/ingress-resources.md
  pkg/alb/lb/loadbalancer.go
  pkg/alb/tg/targetgroups.go
  pkg/alb/tg/targetgroups_test.go
  pkg/albingress/albingress.go
  pkg/albingress/albingress_test.go
  pkg/albingress/albingresses.go
  pkg/albingress/types.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/controller/alb-controller.go
Labels: cncf-cla: yes, size/L

#425 1.0-beta.1
  BUILDING.md
  Makefile
  README.md
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes

#414 Add example with RBAC enabled
  examples/alb-ingress-controller.yaml
  examples/rbac-role.yaml
Labels: cncf-cla: yes, size/M

#427 Update broken readme links
  README.md
Labels: cncf-cla: yes, size/XS

#431 Resolves #429. The cluster name passed to the annotation factory was …
  pkg/alb/tg/targetgroups_test.go
  pkg/albingress/albingress_test.go
  pkg/annotations/annotations.go
  pkg/annotations/annotations_test.go
  pkg/controller/alb-controller.go
Labels: cncf-cla: yes, size/S

#432 Missed some errors when switching to the new requestion.Pagination
  .travis.yml
  pkg/albingress/albingresses.go
  pkg/aws/albelbv2/elbv2.go
  pkg/aws/albrgt/rgt.go
Labels: cncf-cla: yes, size/S

#433 Clarified listen-ports annotation defaults
  docs/ingress-resources.md
Labels: size/XS

#436 Setting all examples to leverage the `kubernetes.io/ingress.class` annotation
  examples/alb-ingress-controller.yaml
  examples/echoservice/echoserver-ingress.yaml
Labels: cncf-cla: yes

#437 Refactored WAF code and added caches
  pkg/alb/lb/loadbalancer.go
  pkg/alb/lb/loadbalancer_test.go
  pkg/alb/lb/types.go
  pkg/annotations/annotations.go
  pkg/annotations/validation.go
  pkg/annotations/validation_fake.go
  pkg/aws/albec2/ec2.go
  pkg/aws/albelbv2/elbv2.go
  pkg/aws/albwaf/waf.go
Labels: cncf-cla: yes, size/L

#438 Updated the image in our helm chart.
  alb-ingress-controller-helm/values.yaml
Labels: cncf-cla: yes

#442 Logging cleanup, cache purging, and a small refactor
  pkg/alb/lb/loadbalancer.go
  pkg/alb/ls/listener.go
  pkg/alb/ls/listener_test.go
  pkg/alb/ls/listeners.go
  pkg/alb/rs/rule.go
  pkg/alb/rs/rules.go
  pkg/alb/tg/targetgroup.go
  pkg/albingress/albingress.go
  pkg/aws/albelbv2/elbv2.go
Labels: cncf-cla: yes, size/L
