Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-09, with the labels that each got.

#585 Fix spelling for walkthrough
  docs/walkthrough.md
Labels: cncf-cla: yes, size/XS

#583 internal/*: remove blank lines (minor)
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/loadbalancer_test.go
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, size/XS

#593 Update owners
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#589 Support for named targetPort and multi-port service
  internal/alb/tg/targetgroup.go
  internal/ingress/backend/endpoint.go
  internal/ingress/backend/endpoint_test.go
  internal/ingress/controller/dummy/service.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
Labels: cncf-cla: yes, size/XL

#590 Filter out redirect loop actions
  internal/alb/ls/listener.go
  internal/alb/ls/listeners_test.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/ingress/annotations/action/main.go
Labels: approved, cncf-cla: yes, size/L

#596 Avoid deprecated SharedInformerFactory API
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#609 wait readiness delay for liveness to start
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#605 Use paginated APIs
  internal/aws/albelbv2/elbv2.go
  internal/aws/albrgt/rgt.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#611 configurable readiness delay in helm chart
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/templates/deployment.yaml
  alb-ingress-controller-helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#607 Subnet tag doc update
  docs/ingress-resources.md
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#610 Catching a nil pointer error
  internal/alb/ls/listener.go
  internal/aws/albec2/ec2.go
  internal/aws/albrgt/rgt.go
  pkg/util/types/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#617 Start to execute AWS healthchecks prior to syncing state
  internal/ingress/controller/alb.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#615 Set the ingress default backend to a 404 response
  internal/alb/ls/listener.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/tg/targetgroups.go
  internal/albingress/albingresses.go
  internal/ingress/annotations/action/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#620 Extract generateID and add tests
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#621 Fixed an NPE when actions are undefined
  internal/ingress/annotations/action/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#623 Added the AWS service to the error messages returned by `Status()`
  internal/aws/albacm/acm.go
  internal/aws/albec2/ec2.go
  internal/aws/albelbv2/elbv2.go
  internal/aws/albiam/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#624 import testify
  Gopkg.lock
  Gopkg.toml
  mocks/ELBV2API.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/constants.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#614 Refactor of securityGroup handling
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/loadbalancer_test.go
  internal/alb/lb/types.go
  internal/alb/ls/listener_test.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/alb/rs/types.go
  internal/alb/sg/association.go
  internal/alb/sg/instance_attachment.go
  internal/alb/sg/lb_attachment.go
  internal/alb/sg/namer.go
  internal/alb/sg/namer_test.go
  internal/alb/sg/security_group.go
  internal/alb/sg/security_group_test.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroup_test.go
  internal/alb/tg/targetgroups_test.go
  internal/alb/tg/types.go
  internal/albingress/albingress.go
  internal/albingress/albingress_test.go
  internal/albingress/albingresses.go
  internal/albingress/types.go
  internal/aws/albec2/ec2.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/ingress/controller/alb.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
  mocks/EC2API.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#627 Fix service annotation merging
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/healthcheck/main.go
  internal/ingress/annotations/healthcheck/main_test.go
  internal/ingress/annotations/listener/main.go
  internal/ingress/annotations/listener/main_test.go
  internal/ingress/annotations/rule/main.go
  internal/ingress/annotations/rule/main_test.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/annotations/targetgroup/main_test.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#636 fix 2048 example
  examples/2048/2048-ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#637 1. Fix issues with targetgroup
  internal/alb/tg/targetgroups.go
  internal/albingress/albingresses.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#641 docs/ingress-resources.md: fix typo in "load-balancer-attributes"
  docs/ingress-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Session level API caching
  cmd/main.go
  go.mod
  go.sum
  internal/alb/ls/listener_test.go
  internal/aws/albcache/cache.go
  internal/aws/albec2/ec2.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/aws/albrgt/rgt.go
  internal/aws/albsession/session.go
  internal/aws/albwafregional/wafregional.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/alb.go
  internal/ingress/controller/dummy/ingress.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/metric/collectors/aws.go
  internal/ingress/metric/collectors/testutils.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  mocks/EC2API.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#647 Updated cache module
  go.mod
  go.sum
  internal/aws/albrgt/rgt.go
  internal/aws/albsession/session.go
  internal/ingress/metric/collectors/aws.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#651 Added controller for target group attributes
  internal/alb/lb/attributes_test.go
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/types.go
  internal/alb/tg/attributes.go
  internal/alb/tg/attributes_test.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/alb/tg/types.go
  internal/albingress/albingress.go
  internal/albingress/albingresses.go
  internal/albingress/types.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/annotations/targetgroup/main_test.go
  internal/ingress/controller/alb.go
  internal/ingress/controller/controller.go
  mocks/ELBV2API.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
