Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-11, with the labels that each got.

#709 Modifications to docs
  docs/README.md
  docs/guide/setup.md
  docs/imgs/controller-design.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#716 Fix new test cases added for Prow
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#713 Fix some typos
  docs/guide/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#719 Migrate coveralls
  .travis.yml
  Makefile
  go.mod
  go.sum
  scripts/ci_unit_test.sh
  scripts/gen_mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#717 fix(docs): Updated link to example iam-policy that was moved per #701.
  docs/guide/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#721 adding golint and goimports check
  .golangci.yml
  cmd/main.go
  go.mod
  go.sum
  internal/alb/ls/listener.go
  internal/alb/sg/lb_attachment.go
  internal/alb/tg/targetgroup.go
  internal/albctx/context.go
  internal/aws/ec2.go
  internal/aws/healthcheck.go
  internal/ingress/controller/config/dynamic.go
  internal/ingress/controller/store/store.go
  internal/ingress/metric/collectors/testutils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#711 Optionally apply default tags to all resources.
  docs/api/configuration.md
  go.mod
  go.sum
  internal/alb/generator/main.go
  internal/alb/generator/tag.go
  internal/alb/generator/tag_test.go
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#729 Fix typos: intance->instance, readbale->readable
  internal/alb/sg/security_group.go
  internal/ingress/metric/collectors/testutils.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#730 Adding tagging support for securityGroup
  .golangci.yml
  docs/api/ingress.md
  docs/examples/iam-policy.json
  internal/alb/generator/name.go
  internal/alb/generator/tag.go
  internal/alb/generator/tag_test.go
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/loadbalancer_test.go
  internal/alb/sg/association.go
  internal/alb/sg/association_test.go
  internal/alb/sg/instance_attachment.go
  internal/alb/sg/lb_attachment.go
  internal/alb/sg/lb_attachment_test.go
  internal/alb/sg/namer.go
  internal/alb/sg/namer_test.go
  internal/alb/sg/security_group.go
  internal/alb/sg/security_group_test.go
  internal/alb/sg/types.go
  internal/alb/tags/mock_Controller.go
  internal/alb/tags/tags.go
  internal/alb/tags/tags_test.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroup_group.go
  internal/alb/tg/targetgroup_test.go
  internal/aws/ec2.go
  internal/aws/ec2_test.go
  internal/aws/elbv2.go
  internal/ingress/controller/controller.go
  mocks/CloudAPI.go
  scripts/gen_mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#732 Allow the target service to be type LoadBalancer or type NodePort
  internal/ingress/backend/endpoint.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#736 fix empty path handling
  internal/alb/rs/rules.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#737 adding make target for docs
  .gitignore
  Makefile
  Pipfile
  Pipfile.lock
Labels: approved, cncf-cla: yes, lgtm, size/L

#738 cut v1.0.0 release
  Makefile
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  cmd/options.go
  docs/README.md
  docs/examples/alb-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#740 Fix #739
  internal/aws/ec2.go
  internal/aws/ec2_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#741 update docker file & examples
  Dockerfile
  docs/examples/2048/2048-ingress.yaml
  docs/examples/echoservice/echoserver-ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#742 migrate to ECR
  .travis.yml
  Makefile
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/templates/deployment.yaml
  alb-ingress-controller-helm/values.yaml
  docs/examples/alb-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#743 Update links in docs to be v1.0.0
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#752 Update examples to be NodePort to be available to all k8s setup on AWS
  docs/examples/2048/2048-service.yaml
  docs/examples/echoservice/echoserver-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#753 fix documentation for integer annotations
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#757 Fixes #748
  docs/examples/iam-policy.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#760 use latest External DNS version 0.5.9
  docs/examples/external-dns.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
