Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-07, with the labels that each got.

#406 Add liveness check against /state
  alb-ingress-controller-helm/templates/controller-deployment.yaml
  alb-ingress-controller-helm/values.yaml
  cmd/main.go
  pkg/aws/albec2/ec2.go
  pkg/controller/alb-controller.go
  pkg/controller/alb-controller_test.go
Labels: cncf-cla: yes, size/M

#448 Adjust indentation to fix a minor markdown rendering issue
  docs/walkthrough.md
Labels: cncf-cla: yes, size/XS

#452 1.0-beta.3
  BUILDING.md
  Makefile
  README.md
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/M

#455 Adopt the kubernetes.io/role/internal-elb and kubernetes.io/role/elb tags
  docs/configuration.md
  docs/ingress-resources.md
  docs/setup.md
  pkg/alb/lb/loadbalancer.go
  pkg/alb/tg/targetgroups.go
  pkg/albingress/albingress.go
  pkg/albingress/albingresses.go
  pkg/annotations/annotations.go
  pkg/aws/albec2/ec2.go
  pkg/aws/albrgt/rgt.go
  pkg/controller/alb-controller.go
Labels: cncf-cla: yes, size/L

#460 Fix readinessProbe timeoutSeconds
  alb-ingress-controller-helm/templates/controller-deployment.yaml
Labels: cncf-cla: yes, size/XS

#461 Fixing a bug where we deregister pod targets on updates
  pkg/alb/tg/targetgroup.go
  pkg/alb/tg/targetgroups.go
Labels: cncf-cla: yes

#462 1.0-beta.4
  BUILDING.md
  Makefile
  README.md
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/S

#466 Allow non-NodePort services when we use the pod target type
  pkg/alb/lb/loadbalancer.go
  pkg/alb/tg/targetgroups.go
  pkg/albingress/albingress.go
  pkg/albingress/albingress_test.go
  pkg/albingress/albingresses.go
  pkg/controller/alb-controller.go
  pkg/controller/alb-controller_test.go
Labels: cncf-cla: yes, size/M

#468 When using pod targets we need to check if the pod IP is outside of t…
  examples/iam-policy.json
  pkg/alb/lb/loadbalancer.go
  pkg/alb/tg/targetgroup.go
  pkg/alb/tg/targetgroups.go
  pkg/aws/albec2/ec2.go
  pkg/aws/albelbv2/elbv2.go
Labels: cncf-cla: yes, size/M

#477 Minor update
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/XS

#479 Support KOPS values for private/public subnet tags
  pkg/aws/albrgt/rgt.go
Labels: cncf-cla: yes, size/XS

#481 Add DescribeSSLPolicies to iam-policy.json
  examples/iam-policy.json
Labels: cncf-cla: yes, size/XS

#483 Repackage ingress addenda
  Makefile
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/templates/_helpers.tpl
  alb-ingress-controller-helm/templates/deployment.yaml
  alb-ingress-controller-helm/values.yaml
  docs/configuration.md
  docs/setup.md
  docs/walkthrough.md
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/M

#484 removed some unused code
  internal/alb/lb/loadbalancer.go
  internal/albingress/albingress.go
  internal/albingress/albingresses.go
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, size/M

#486 Adds CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: cncf-cla: yes, sig/contributor-experience, size/XS

#489 Fix wildcard value
  internal/aws/albrgt/rgt.go
Labels: cncf-cla: yes, size/XS

#485 move helm controller values to root
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/templates/deployment.yaml
  alb-ingress-controller-helm/values.yaml
Labels: cncf-cla: yes, size/L

#491 Update iam-policy.json.
  examples/iam-policy.json
Labels: cncf-cla: yes, size/XS

#492 Added the option to provide a default target type.
  cmd/flags.go
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/loadbalancer_test.go
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/alb/ls/listeners.go
  internal/alb/ls/listeners_test.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/alb/tg/targetgroups_test.go
  internal/albingress/albingress.go
  internal/albingress/albingress_test.go
  internal/albingress/albingresses.go
  internal/albingress/types.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/loadbalancer/main.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/alb.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
  internal/ingress/resolver/main.go
  internal/ingress/resolver/mock.go
Labels: cncf-cla: yes, size/XXL

#497 TargetGroup names are not unique enough in the current state
  internal/alb/tg/targetgroup.go
  internal/ingress/controller/alb.go
Labels: cncf-cla: yes, size/S

#508 small refactoring in lb to start to unravel managed sg
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/types.go
Labels: cncf-cla: yes, size/L

#503 Kubernetes 1.11 has removed ExternalID
  Gopkg.lock
  internal/ingress/controller/store/store.go
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: cncf-cla: yes, size/XL

#512 Leverage the EC2 state when building a list of cluster nodes
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/aws/albec2/ec2.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/ingress/controller/store/store.go
  internal/ingress/status/status.go
Labels: cncf-cla: yes, size/M

#513 Correct typo in backend-protocol annotation
  cmd/flags.go
  internal/alb/tg/targetgroup.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/healthcheck/main.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/config/config.go
  pkg/util/log/log.go
Labels: cncf-cla: yes, size/M

#514 1.0-beta.5
  Makefile
  README.md
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  examples/alb-ingress-controller.yaml
Labels: cncf-cla: yes, size/S

#516 Added missing IAM policy
  examples/iam-policy.json
Labels: cncf-cla: yes, size/XS

#517 Cache node lookup errors for a shorter time
  internal/aws/albec2/ec2.go
Labels: cncf-cla: yes, size/XS
