Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-08, with the labels that each got.

#519 Improve error message
  internal/aws/albec2/ec2.go
Labels: cncf-cla: yes

#523 Added rbac deployment to walkthrough
  docs/walkthrough.md
Labels: cncf-cla: yes

#524 Fix a type mismatch that was detected in #507
  internal/aws/albec2/ec2.go
Labels: cncf-cla: yes

#528 updated values table
  alb-ingress-controller-helm/README.md
Labels: cncf-cla: yes, size/S

#531 Fixes IAM policy for Associating / Dissociating regional waf
  examples/iam-policy.json
Labels: cncf-cla: yes, size/S

#529 Support named ports
  internal/alb/lb/loadbalancer.go
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/alb/ls/listeners.go
  internal/alb/ls/listeners_test.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/alb/rs/types.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/alb/tg/types.go
  internal/ingress/controller/alb.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/L

#535 Continue to use the deprecated node external id through 1.10
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/XS

#537 Support default IngressBackends
  internal/alb/lb/loadbalancer.go
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/alb/ls/types.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/alb/tg/dummy.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/alb/tg/targetgroups_test.go
  internal/albingress/albingress.go
  internal/albingress/albingresses.go
  internal/aws/albelbv2/dummy.go
  internal/aws/albelbv2/elbv2.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
  pkg/util/types/tags.go
Labels: approved, cncf-cla: yes, size/XL

#538 Made the TG hashed name longer
  internal/alb/tg/targetgroup.go
Labels: approved, cncf-cla: yes, size/S

#539 Fixed invalid target type created in #538
  internal/alb/tg/targetgroup.go
Labels: approved, cncf-cla: yes, size/XS

#540 Don't register empty lists of targets
  internal/alb/tg/targetgroup.go
Labels: approved, cncf-cla: yes, size/XS

#542 Customized ALB actions
  docs/ingress-resources.md
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/loadbalancer_test.go
  internal/alb/lb/types.go
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/alb/ls/listeners.go
  internal/alb/ls/listeners_test.go
  internal/alb/ls/types.go
  internal/alb/rs/rule.go
  internal/alb/rs/rule_test.go
  internal/alb/rs/rules.go
  internal/alb/rs/rules_test.go
  internal/alb/rs/types.go
  internal/alb/tg/dummy.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroups.go
  internal/alb/tg/targetgroups_test.go
  internal/albingress/albingress.go
  internal/albingress/albingress_test.go
  internal/aws/albec2/ec2.go
  internal/ingress/annotations/action/main.go
  internal/ingress/annotations/action/main_test.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/loadbalancer/main.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/dummy/ingress.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/store.go
  pkg/util/log/log.go
Labels: approved, cncf-cla: yes, size/XL

#544 Changed target type 'pod' to 'ip' which better matches AWS
  cmd/flags.go
  internal/alb/tg/targetgroup.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/M

#545 1.0-beta.6
  Makefile
  README.md
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  examples/alb-ingress-controller.yaml
Labels: approved, size/L

#547 Missed a couple of mentions of `pod` in the docs
  docs/ingress-resources.md
Labels: approved, cncf-cla: yes, size/XS

#553 Updated the docs to build a cluster with eksctl
  docs/walkthrough.md
  examples/alb-ingress-controller.yaml
  examples/echoservice/echoserver-ingress.yaml
  examples/echoservice/echoserver-service.yaml
Labels: approved, cncf-cla: yes, size/L

#549 Validate node's providerID in case it's empty
  docs/setup.md
  internal/ingress/controller/store/store.go
Labels: cncf-cla: yes, size/S

#554 Fixing some prometheus measurements
  internal/albingress/albingress.go
  internal/albingress/albingress_test.go
  internal/albingress/albingresses.go
  internal/albingress/types.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/controller.go
  internal/ingress/metric/collectors/aws.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
Labels: approved, cncf-cla: yes, size/L

#555 merge master
  docs/ingress-resources.md
  docs/setup.md
  docs/walkthrough.md
  examples/alb-ingress-controller.yaml
  examples/echoservice/echoserver-ingress.yaml
  examples/echoservice/echoserver-service.yaml
  internal/albingress/albingress.go
  internal/albingress/albingress_test.go
  internal/albingress/albingresses.go
  internal/albingress/types.go
  internal/ingress/annotations/targetgroup/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/store.go
  internal/ingress/metric/collectors/aws.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
Labels: cncf-cla: yes, size/L

#564 walkthrough.md: fix indentation for code block
  docs/walkthrough.md
Labels: cncf-cla: yes, size/M

#565 Revert "walkthrough.md: fix indentation for code block"
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, size/M

#562 [elbv2/PopulateAZ] Support VPC with secondary CIDR ranges
  internal/aws/albelbv2/elbv2.go
Labels: cncf-cla: yes, size/S

#567 Updated 2048 annotations to correct target-type var
  examples/2048/2048-ingress.yaml
  examples/2048/2048-service.yaml
Labels: approved

#566 walkthrough.md: fix indentation for code block
  docs/walkthrough.md
Labels: cncf-cla: yes, size/M

#581 cmd/main.go: remove unnecessary blank line
  cmd/main.go
Labels: cncf-cla: yes, size/XS
