Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2018-12, with the labels that each got.

#764 bump golangcli-lint version to v1.12.3
  .travis.yml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#763 Fix kubectl apply command for echoserver
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#767 fix incompatible tagging on securityGroups with core k8s
  internal/alb/generator/tag.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#768 fix controller crash when action annotation didn't exists
  internal/ingress/annotations/action/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#769 cut release 1.0.1
  Makefile
  alb-ingress-controller-helm/Chart.yaml
  alb-ingress-controller-helm/README.md
  alb-ingress-controller-helm/values.yaml
  docs/README.md
  docs/examples/alb-ingress-controller.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#744 adding helm-repo as github pages
  Pipfile
  Pipfile.lock
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#781 Corrected indentation in example
  docs/guide/tasks/ssl_redirect.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#788 Fix shutdown logging
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
