Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-04, with the labels that each got.

#915 Fix UT failure due to coverall
  go.mod
  go.sum
  scripts/ci_unit_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#904 Add support for shared subnets
  internal/alb/lb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#903 Add idle_timeout.timeout_seconds annotation docs
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#926 Fix panic when deleting an ALB with no default SG in the VPC
  internal/alb/sg/lb_attachment.go
  internal/alb/sg/lb_attachment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#923 enhance certificate auto-discover functionality
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/aws/acm.go
  mocks/CloudAPI.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#931 add permission to use cognito
  docs/examples/iam-policy.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
