Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-03, with the labels that each got.

#881 cut v1.1.2 release
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#890 Update ingress docs for authentication
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#882 Added configuration page for ALB Ingress Controller with Cognito auth.
  docs/guide/cognito/setup.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#900 Scopes must be space-separated list
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#902 Fix extra hyphen in ingress-controller example
  docs/examples/alb-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
