Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-02, with the labels that each got.

#809 Syntax fixing on Verify the deployment
  docs/guide/controller/setup.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, ok-to-test, size/XS

#852 add initial set of e2e test
  Makefile
  cmd/main.go
  cmd/options.go
  go.mod
  go.sum
  internal/aws/rgt.go
  internal/aws/session.go
  scripts/ci_e2e_test.sh
  scripts/ci_unit_test.sh
  scripts/utils/cluster.sh
  scripts/utils/ecr.sh
  test/e2e/framework/cleanup.go
  test/e2e/framework/framework.go
  test/e2e/framework/options.go
  test/e2e/framework/resource/deployment.go
  test/e2e/framework/resource/ingress.go
  test/e2e/framework/resource/manager.go
  test/e2e/framework/resource/namespace.go
  test/e2e/framework/resource/service.go
  test/e2e/framework/utils/constants.go
  test/e2e/framework/utils/log.go
  test/e2e/framework/utils/name.go
  test/e2e/ingress/multi_path_echo.go
  test/e2e/ingress/shared/resources.go
  test/e2e/ingress/shared/targets.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#857 fix issue 838
  internal/alb/sg/association.go
  internal/alb/sg/instance_attachment.go
  internal/aws/ec2.go
  mocks/CloudAPI.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#851 Auto-add certs from ACM by hostname if none are specified via annotation
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/aws/acm.go
  mocks/CloudAPI.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#862 Makefile: tag container with latest version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#863 Add DescribeNetworkInterfaces to sample iam policy
  docs/examples/iam-policy.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#864 Refactor/PR comments for auto-cert matching + documentation
  docs/guide/ingress/annotation.md
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#872 fix typo in docs
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#876 Add a .dockerignore file to speed up image building
  .dockerignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#875 Add template for Cognito integrated ALB ingress
  docs/examples/cognito-ingress-template.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#877 Add support for pod IP targets outside of the VPC
  internal/alb/tg/targets.go
  internal/alb/tg/targets_test.go
  internal/aws/ec2.go
  mocks/CloudAPI.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#878 remove aws api cache
  cmd/main.go
  internal/aws/cloud.go
  internal/aws/session.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#880 fix AWS API available detection
  internal/aws/acm.go
  internal/aws/wafregional.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
