Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-09, with the labels that each got.

#1009 Switch to use new test framework
  .gitignore
  Makefile
  go.mod
  go.sum
  tester/cmd/main.go
  tester/test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1024 Update the Travis go version
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1025 adding cache for cert discovery
  internal/alb/ls/cert_discovery.go
  internal/alb/ls/cert_discovery_test.go
  internal/alb/ls/listener.go
  internal/alb/ls/listener_test.go
  internal/utils/cache.go
  internal/utils/cache_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1026 upgrade aws-sdk to use iam-for-pods
  go.mod
  go.sum
  mocks/ACMAPI.go
  mocks/EC2API.go
  mocks/ELBV2API.go
  mocks/IAMAPI.go
  mocks/ResourceGroupsTaggingAPIAPI.go
  mocks/WAFRegionalAPI.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1027 cut v1.1.3 release
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1030 fix sg rule handling bug when scale down to 0 under ip mode
  internal/alb/sg/instance_attachment_v2.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
