Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-12, with the labels that each got.

#1063 enhance ip mode for non-ec2 nodes
  Dockerfile
  go.mod
  go.sum
  internal/alb/sg/instance_attachment_v1.go
  internal/alb/sg/instance_attachment_v2.go
  internal/alb/sg/target_enis_resolver.go
  internal/aws/cloud.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/mock_Storer.go
  internal/ingress/controller/store/store.go
  internal/utils/strings.go
  mocks/CloudAPI.go
  test/e2e/framework/framework.go
  test/e2e/framework/options.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1079 fix ingress example
  docs/guide/ingress/spec.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1067 fixup docs for load-balancer-attributes
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1087 Load balancing algorithm for target groups support
  docs/guide/ingress/annotation.md
  internal/alb/tg/attributes.go
  internal/alb/tg/attributes_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1095 update to latest version
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1096 fixup docs for deployment example
  docs/examples/2048/2048-deployment.yaml
  docs/examples/echoservice/echoserver-deployment.yaml
  docs/examples/external-dns.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1114 docs(echoserver.md): fix typos
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
