Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-07, with the labels that each got.

#963 Removed andrewtandoc
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#968 add flag to enable concurrent reconciliation.
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#958 Added docs for creating DNS pointing from ingress object
  docs/guide/external-dns/setup.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
