Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2019-08, with the labels that each got.

#1001 fix_lint
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#991 IPv6 Support in Inbound CIDR Annotation
  internal/alb/sg/association.go
  internal/alb/sg/security_group.go
  internal/alb/sg/security_group_test.go
  internal/ingress/annotations/loadbalancer/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1004 Switch to use multi stage build for container
  .dockerignore
  Dockerfile
  Makefile
  scripts/ci_e2e_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
