Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-12, with the labels that each got.

#1705 update docs to point to 2.1.0 spec
  docs/guide/controller/installation.md
Labels: cncf-cla: yes, size/XS

#1681 promote install instructions to top level menu item, enable mkdocs gh action
  docs/deploy/configurations.md
  docs/deploy/installation.md
  docs/deploy/pod_readiness_gate.md
  docs/deploy/subnet_discovery.md
  docs/deploy/upgrade/migrate_v1_v2.md
  docs/examples/echo_server.md
  docs/guide/controller/installation.md
  docs/guide/ingress/annotations.md
  docs/guide/service/annotations.md
  docs/guide/tasks/cognito_authentication.md
  docs/how-it-works.md
  mkdocs.yml
Labels: cncf-cla: yes, lgtm, size/L

#1710 doc: fix wrong itemization format
  docs/how-it-works.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1716 Fix list in how-it-works doc
  docs/how-it-works.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1713 Enable e2e with Prow
  Makefile
  go.mod
  go.sum
  scripts/ci_e2e_test.sh
  scripts/ci_unit_test.sh
  scripts/lib/ecr.sh
  scripts/lib/eksctl.sh
  scripts/lib/eksctl_tmpl_cluster.yaml
  scripts/lib/iam.sh
  test/e2e/ingress/ingress_suite_test.go
  test/e2e/ingress/multi_path_backend_test.go
  test/e2e/service/service_suite_test.go
  test/e2e/service/service_test.go
  test/framework/controller/constants.go
  test/framework/controller/installation_manager.go
  test/framework/framework.go
  test/framework/helm/release_manager.go
  test/framework/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1722 Fix annotation documentation about ALB attributes
  docs/guide/ingress/annotations.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1746 Update service annotation doc
  docs/guide/service/annotations.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1730 fix typo in docs/deploy/installation.md
  docs/deploy/installation.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1727 ignore target group health check timeout for NLB
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#1741 Download latest al2 packages during docker build
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
