Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-04, with the labels that each got.

#1215 Removed micahhausler as reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS

#1206 Make options consistent
  docs/examples/alb-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1213 don't crash on large objets served by recent k8s-api-server
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1216 Strip trailing newlines from OIDC clientId
  internal/ingress/auth/auth.go
  internal/ingress/auth/auth_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1207 Add the Delete Invalid Headers section to the doc
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1214 React on pod events for readiness gates
  internal/ingress/backend/endpoint.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/handlers/pod.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1211 WAFv2 support
  docs/examples/iam-policy.json
  docs/guide/ingress/annotation.md
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/wafv2.go
  internal/alb/lb/wafv2_test.go
  internal/aws/cloud.go
  internal/aws/wafv2.go
  internal/aws/wafv2_test.go
  internal/ingress/controller/config/features.go
  internal/ingress/controller/store/mock_Storer.go
  mocks/CloudAPI.go
  mocks/WAFV2API.go
  scripts/gen_mocks.sh
  tester/test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1228 redact oidc
  internal/alb/ls/listener.go
  internal/alb/ls/rules.go
  internal/alb/ls/rules_test.go
  pkg/util/deepcopy.go
  pkg/util/deepcopy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1229 release v1.1.7
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, size/M
