Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-10, with the labels that each got.

#1469 finalize user-facing elements(finalizer/tagging/labeling)
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  go.mod
  go.sum
  mocks/aws/services/mock_ec2.go
  mocks/k8s/mock_finalizer.go
  mocks/networking/mock_security_group_manager.go
  pkg/annotations/constants.go
  pkg/deploy/ec2/security_group_manager.go
  pkg/deploy/ec2/security_group_synthesizer.go
  pkg/deploy/ec2/tagging_manager.go
  pkg/deploy/ec2/tagging_manager_test.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler_test.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_synthesizer.go
  pkg/deploy/elbv2/load_balancer_synthesizer_test.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/elbv2/target_group_attributes_reconciler_test.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_synthesizer.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/elbv2/target_group_synthesizer_test.go
  pkg/deploy/stack_deployer.go
  pkg/deploy/stack_marshaller_test.go
  pkg/deploy/stack_schema_builder.go
  pkg/deploy/stack_schema_builder_test.go
  pkg/deploy/tagging/provider.go
  pkg/deploy/tagging/provider_test.go
  pkg/deploy/tracking/provider.go
  pkg/deploy/tracking/provider_test.go
  pkg/deploy/tracking/tag_filter.go
  pkg/deploy/tracking/tag_filter_test.go
  pkg/ingress/finalizer.go
  pkg/ingress/finalizer_test.go
  pkg/ingress/group.go
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
  pkg/ingress/group_test.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/ingress/patches.go
  pkg/model/core/stack.go
  pkg/model/core/stack_id.go
  pkg/model/core/stack_test.go
  pkg/model/core/token_types_test.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, size/XXL

#1472 retry listenerRule creation in place when ListenerNotFound
  pkg/deploy/ec2/security_group_manager.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_manager.go
Labels: cncf-cla: yes, size/M

#1474 Enable security hardening options
  Dockerfile
  config/controller/kustomization.yaml
  config/controller/security_context_patch.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1471 add service/secret eventHandler for ingress
  controllers/elbv2/eventhandlers/endpoints.go
  controllers/elbv2/eventhandlers/node.go
  controllers/elbv2/suite_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/eventhandlers/ingress_events.go
  controllers/ingress/eventhandlers/secret_events.go
  controllers/ingress/eventhandlers/service_events.go
  controllers/ingress/group_controller.go
  controllers/service/eventhandlers/service_events.go
  controllers/service/service_controller.go
  main.go
  pkg/ingress/auth_config_builder.go
  pkg/ingress/auth_config_builder_test.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/reference_indexer.go
  pkg/ingress/reference_indexer_test.go
Labels: cncf-cla: yes, size/XXL

#1473 Updated nlb-ip with more details around proxy protocol
  docs/guide/nlb-ip.md
Labels: cncf-cla: no, needs-ok-to-test, size/XS

#1476 add docs for ingress/service and overall docs layout
  deploy/ingress.yaml
  docs/README.md
  docs/assets/images/aws_load_balancer_icon.svg
  docs/guide/controller/configurations.md
  docs/guide/controller/installation.md
  docs/guide/controller/subnet_discovery.md
  docs/guide/ingress/annotations.md
  docs/guide/ingress/cert_discovery.md
  docs/guide/integrations/external_dns.md
  docs/guide/migration.md
  docs/guide/nlb-ip.md
  docs/guide/service/annotations.md
  docs/guide/service/nlb_ip_mode.md
  docs/guide/tasks/cognito_authentication.md
  docs/guide/tasks/ssl_redirect.md
  docs/guide/upgrade/migrate_v1_v2.md
  docs/guide/walkthrough/echo_server.md
  mkdocs.yml
Labels: cncf-cla: yes, size/XXL

#1477 crd adjustments & webhook-secret name change
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  config/certmanager/certificate.yaml
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  config/default/controller_webhook_patch.yaml
Labels: cncf-cla: yes, size/S

#1478 promote targetgroupbinding api from v1alpha1 to v1beta1
  apis/elbv2/v1beta1/groupversion_info.go
  apis/elbv2/v1beta1/targetgroupbinding_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  controllers/elbv2/eventhandlers/endpoints.go
  controllers/elbv2/eventhandlers/node.go
  controllers/elbv2/targetgroupbinding_controller.go
  main.go
  pkg/backend/endpoint_utils.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_synthesizer.go
  pkg/ingress/model_build_target_group.go
  pkg/inject/pod_readiness_gate.go
  pkg/inject/pod_readiness_gate_test.go
  pkg/k8s/finalizer_test.go
  pkg/model/elbv2/target_group_binding.go
  pkg/service/nlb/builder.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/utils.go
  webhooks/elbv2/targetgroupbinding_mutator.go
  webhooks/elbv2/targetgroupbinding_mutator_test.go
  webhooks/elbv2/targetgroupbinding_validator.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
Labels: cncf-cla: yes, size/XL

#1479 Add feature gates for ALB addons
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/guide/service/nlb_ip_mode.md
  go.mod
  main.go
  pkg/aws/cloud.go
  pkg/aws/cloud_config.go
  pkg/config/addons_config.go
  pkg/config/controller_config.go
  pkg/config/ingress_config.go
  pkg/config/runtime_config.go
  pkg/deploy/stack_deployer.go
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1484 [v2] fix multiple bugs
  pkg/aws/errors/utils.go
  pkg/equality/elbv2/compare_option_for_actions.go
  pkg/equality/elbv2/compare_option_for_actions_test.go
  pkg/ingress/config_types.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_builder.go
  pkg/ingress/rule_optimizer.go
  pkg/ingress/rule_optimizer_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/XXL

#1490 changed webhook secret name to be aws-load-balancer-webhook-tls
  config/certmanager/certificate.yaml
  config/default/controller_webhook_patch.yaml
Labels: cncf-cla: yes, size/XS

#1491 cut v2.0.0-rc3 release
  Makefile
  config/controller/kustomization.yaml
  config/samples/install_v2_0_0_rc3.yaml
  config/webhook/manifests.v1beta1.yaml
  controllers/ingress/group_controller.go
  webhooks/elbv2/targetgroupbinding_mutator.go
  webhooks/elbv2/targetgroupbinding_validator.go
Labels: cncf-cla: yes, size/XL

#1492 Add support for specifying source ranges for NLB
  pkg/annotations/constants.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1493 hard-code ingressClass to alb & adjust memory limit
  config/controller/controller.yaml
  config/samples/install_v2_0_0_rc3.yaml
Labels: cncf-cla: yes, size/XS

#1495 add test framework
  test/framework/framework.go
  test/framework/options.go
  test/framework/resources/k8s/deployment.go
  test/framework/resources/k8s/ingresses.go
  test/framework/resources/k8s/namespace.go
  test/framework/resources/k8s/service.go
  test/framework/utils/log.go
  test/framework/utils/multi_error.go
  test/framework/utils/name.go
  test/framework/utils/poll.go
Labels: cncf-cla: yes, size/L

#1498 fix the iam permissions
  docs/guide/upgrade/migrate_v1_v2.md
  docs/install/iam_policy.json
  docs/install/iam_policy_v1_to_v2_additional.json
Labels: cncf-cla: yes, size/L

#1497 Fix addons_config default values
  pkg/config/addons_config.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1499 add AWS Load Balancer Controller info
  README.md
Labels: approved, cncf-cla: yes, size/S

#1502 add e2e test for Ingress
  test/e2e/ingress/ingress_suite_test.go
  test/e2e/ingress/multi_path_backend.go
  test/e2e/ingress/multi_path_backend_test.go
  test/e2e/ingress/resource_stack.go
  test/e2e/ingress/utils.go
  test/framework/framework.go
  test/framework/http/matcher.go
  test/framework/http/response.go
  test/framework/http/verifier.go
  test/framework/resources/aws/load_balancer.go
  test/framework/utils/dns.go
Labels: cncf-cla: yes, size/XXL

#1503 Fix NLB model for supporting multiple certificate ARNs
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1504 multiple bug fix and code style changes
  controllers/elbv2/eventhandlers/endpoints.go
  controllers/elbv2/eventhandlers/node.go
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/eventhandlers/ingress_events.go
  controllers/ingress/eventhandlers/secret_events.go
  controllers/ingress/eventhandlers/service_events.go
  controllers/ingress/group_controller.go
  controllers/service/eventhandlers/service_events.go
  controllers/service/service_controller.go
  main.go
  pkg/deploy/stack_deployer.go
  pkg/k8s/events.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/targetgroupbinding/utils.go
  test/e2e/ingress/multi_path_backend.go
Labels: cncf-cla: yes, size/L

#1500 Add e2e tests for NLB IP mode
  Makefile
  pkg/aws/cloud.go
  pkg/aws/services/rgt.go
  test/e2e/service/service.go
  test/e2e/service/service_suite_test.go
  test/e2e/service/service_test.go
  test/framework/resources/k8s/service.go
  test/framework/utils/name.go
  test/framework/utils/poll.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#1505 add throttle cfg for waf
  pkg/aws/throttle/defaults.go
Labels: cncf-cla: yes, size/M

#1506 add support for version & adjust flags
  Dockerfile
  controllers/elbv2/targetgroupbinding_controller.go
  main.go
  pkg/config/controller_config.go
  pkg/config/runtime_config.go
  pkg/runtime/concise_logger.go
  pkg/runtime/concise_logger_test.go
  pkg/version/version.go
Labels: cncf-cla: yes, size/L

#1507 add unit tests and fix annotation-based forward
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/guide/ingress/annotations.md
  mocks/ingress/mock_cert_discovery.go
  mocks/networking/mock_subnet_resolver.go
  pkg/ingress/config_types.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/enhanced_backend_builder_test.go
  pkg/ingress/model_builder_test.go
  pkg/model/elbv2/listener_rule.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, size/XXL

#1508 fix AWS SDK session
  pkg/aws/cloud.go
Labels: cncf-cla: yes, size/XS

#1510 add ability for targetGroupBinding to change networking
  controllers/elbv2/targetgroupbinding_controller.go
  go.mod
  go.sum
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/L

#1509 Installation guide
  CONTRIBUTING.md
  LICENSE
  SECURITY_CONTACTS
  code-of-conduct.md
  docs/CONTRIBUTING.md
  docs/assets/images/controller-design.png
  docs/assets/images/subnet-tags.png
  docs/code-of-conduct.md
  docs/examples/2048/2048-deployment.yaml
  docs/examples/2048/2048-ingress.yaml
  docs/examples/2048/2048-namespace.yaml
  docs/examples/2048/2048-service.yaml
  docs/examples/cognito-ingress-template.yaml
  docs/examples/echoservice/echoserver-deployment.yaml
  docs/examples/echoservice/echoserver-ingress.yaml
  docs/examples/echoservice/echoserver-namespace.yaml
  docs/examples/echoservice/echoserver-service.yaml
  docs/examples/external-dns.yaml
  docs/guide/controller/configurations.md
  docs/guide/controller/how-it-works.md
  docs/guide/controller/installation.md
  docs/guide/controller/subnet_discovery.md
  docs/guide/ingress/spec.md
  docs/guide/integrations/external_dns.md
  docs/guide/tasks/cognito_authentication.md
  docs/guide/tasks/migrate_legacy_apps.md
  docs/guide/tasks/ssl_redirect.md
  docs/guide/walkthrough/echo_server.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XXL

#1512 Update configurations doc
  docs/guide/controller/configurations.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1514 cutting v2.0.0-rc4 release
  Makefile
  config/controller/kustomization.yaml
  config/samples/install_v2_0_0_rc4.yaml
Labels: cncf-cla: yes, size/XL

#1518 multiple bug fixes for v2.0.0-rc4
  docs/guide/ingress/annotations.md
  main.go
  pkg/deploy/elbv2/target_group_binding_synthesizer.go
  pkg/deploy/stack_deployer.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_actions_test.go
  pkg/k8s/finalizer.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
  pkg/targetgroupbinding/targets_manager_types.go
  pkg/targetgroupbinding/targets_manager_types_test.go
Labels: cncf-cla: yes, size/XL

#1520 improve performance
  pkg/equality/ec2/compare_option_for_ip_permission.go
  pkg/networking/security_group_info.go
  pkg/networking/security_group_info_test.go
  pkg/networking/security_group_reconciler.go
  pkg/networking/security_group_reconciler_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/XL

#1522 Target group name based on target port
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1523 use numeric target group if available
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1526 Tighten RBAC permissions
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1528 optimize the memory usage and fix bugs
  main.go
  mocks/k8s/mock_repo_info_repo.go
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/backend/endpoint_types.go
  pkg/backend/endpoint_types_test.go
  pkg/ingress/reference_indexer.go
  pkg/k8s/conversion_store.go
  pkg/k8s/pod_info.go
  pkg/k8s/pod_info_repo.go
  pkg/k8s/pod_info_repo_test.go
  pkg/k8s/pod_info_test.go
  pkg/networking/node_eni_info_resolver.go
  pkg/networking/node_eni_info_resolver_test.go
  pkg/networking/pod_eni_info_resolver.go
  pkg/networking/pod_eni_info_resolver_test.go
  pkg/runtime/errors.go
  pkg/runtime/errors_test.go
  pkg/runtime/reconcile.go
  pkg/runtime/reconcile_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, size/XXL

#1529 fix eniInfo parsing from annotation
  pkg/k8s/pod_info.go
  pkg/k8s/pod_info_test.go
  pkg/networking/pod_eni_info_resolver.go
Labels: cncf-cla: yes, size/L

#1527 Allow patch for events
  config/rbac/role.yaml
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1530 add liveness probe and adjust cpu/mem limit
  config/controller/controller.yaml
  main.go
  pkg/config/runtime_config.go
Labels: cncf-cla: yes, size/S

#1531 fix aws session metrics
  pkg/aws/cloud.go
Labels: cncf-cla: yes, size/M

#1536 Update slow_start.duration_seconds example to specify a valid value.
  docs/guide/ingress/annotations.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1539 updating the 2048 game example
  docs/examples/2048/2048-deployment.yaml
  docs/examples/2048/2048-ingress.yaml
  docs/examples/2048/2048-namespace.yaml
  docs/examples/2048/2048-service.yaml
  docs/examples/2048/2048_full.yaml
Labels: cncf-cla: yes, size/L

#1538 add bages to readme
  docs/README.md
Labels: cncf-cla: yes, size/S

#1537 add v2.0.0 manifest and strict leaderelection rbac
  Makefile
  config/controller/kustomization.yaml
  config/rbac/leader_election_role.yaml
  docs/install/v2_0_0_full.yaml
Labels: cncf-cla: yes, size/XL

#1540 add TargetGroupBinding docs
  apis/elbv2/v1beta1/targetgroupbinding_types.go
  docs/guide/ingress/spec.md
  docs/guide/targetgroupbinding/spec.md
  docs/guide/targetgroupbinding/targetgroupbinding.md
  hack/api-docs/config.json
  hack/api-docs/template/members.tpl
  hack/api-docs/template/pkg.tpl
  hack/api-docs/template/type.tpl
  mkdocs.yml
Labels: cncf-cla: yes, size/XL

#1541 update migration doc to include more information
  docs/guide/upgrade/migrate_v1_v2.md
Labels: cncf-cla: yes, size/M

#1517 Fix documentation for contribution and building
  CONTRIBUTING.md
  docs/BUILDING.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1542 fix typo in the migration docs
  docs/guide/upgrade/migrate_v1_v2.md
Labels: cncf-cla: yes, size/XS

#1543 refine logos in readme
  docs/README.md
  docs/assets/images/aws_load_balancer_icon.svg
Labels: cncf-cla: yes, size/M

#1544 add kubernetes logo
  docs/assets/images/kubernetes_icon.svg
Labels: cncf-cla: yes, size/L

#1548 update install doc and migration iam policy
  docs/guide/controller/installation.md
  docs/install/iam_policy_v1_to_v2_additional.json
  mkdocs.yml
Labels: cncf-cla: yes, size/L

#1549 update docs website link
  docs/README.md
Labels: cncf-cla: yes, size/XS

#1551 Add readiness gate documentation
  docs/guide/controller/pod_readiness_gate.md
Labels: cncf-cla: yes, size/M

#1554 Undo resourceName restriction on leader election role
  config/rbac/leader_election_role.yaml
  docs/install/v2_0_0_full.yaml
Labels: cncf-cla: yes, size/XS

#1555 fix RBAC permission
  config/rbac/leader_election_role.yaml
  docs/install/v2_0_0_full.yaml
Labels: cncf-cla: yes, size/S

#1564 add readinessGate doc into website and migration guide
  docs/guide/upgrade/migrate_v1_v2.md
  mkdocs.yml
Labels: cncf-cla: yes, size/XS

#1560 add iam-policy-cn.json to support aws-cn(AWS China regions) partition
  docs/install/iam-policy-cn.json
Labels: cncf-cla: yes, size/L

#1574 Update echo_server.md
  docs/guide/walkthrough/echo_server.md
Labels: cncf-cla: yes, size/XS

#1553 fix: iam policy about targetgroup
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_v1_to_v2_additional.json
Labels: cncf-cla: yes, size/S

#1596 doc updates
  Makefile
  docs/guide/controller/installation.md
Labels: cncf-cla: yes, size/XS
