Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-01, with the labels that each got.

#1104 docs: update example for ExternalDNS
  docs/guide/external-dns/setup.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1088 Advanced routing/weighted loadbalancing support
  .golangci.yml
  docs/guide/ingress/annotation.md
  go.mod
  go.sum
  internal/alb/ls/listener_test.go
  internal/alb/ls/rules.go
  internal/alb/ls/rules_comp.go
  internal/alb/ls/rules_comp_test.go
  internal/alb/ls/rules_test.go
  internal/alb/tg/targetgroup_group.go
  internal/alb/tg/targetgroup_group_test.go
  internal/ingress/annotations/action/main.go
  internal/ingress/annotations/action/main_test.go
  internal/ingress/annotations/action/types.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/conditions/main.go
  internal/ingress/annotations/conditions/main_test.go
  internal/ingress/annotations/conditions/types.go
  mocks/EC2API.go
  mocks/ResourceGroupsTaggingAPIAPI.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1109 Rewrite GetClusterSubnets() using EC2 specific API
  internal/alb/lb/loadbalancer.go
  internal/aws/ec2.go
  internal/aws/ec2_test.go
  internal/aws/rgt.go
  internal/aws/rgt_test.go
  mocks/CloudAPI.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1128 adding cache around WAF API usage
  internal/alb/lb/loadbalancer.go
  internal/alb/lb/waf.go
  internal/alb/lb/waf_test.go
  internal/ingress/annotations/loadbalancer/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1129 ignore fargate nodes for instance target type
  internal/ingress/annotations/class/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1091 Use main from e2e tester
  Makefile
  go.mod
  go.sum
  tester/cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1130 cut v1.1.5 release
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1136 Add ALB attribute to configure dropping invalid headers
  internal/alb/lb/attributes.go
  internal/alb/lb/attributes_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
