Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-08, with the labels that each got.

#1343 V2 ga api el
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
Labels: cncf-cla: yes, size/S

#1342 add targets manager
  mocks/aws/services/mock_elbv2.go
  pkg/targetgroupbinding/targets_manager.go
  pkg/targetgroupbinding/targets_manager_test.go
  pkg/targetgroupbinding/targets_manager_types.go
  pkg/targetgroupbinding/targets_manager_types_test.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, size/XXL

#1347 add resource model for securityGroup and Loadbalancer
  pkg/model/core/resource.go
  pkg/model/core/stack.go
  pkg/model/core/token_types.go
  pkg/model/ec2/security_group.go
  pkg/model/elbv2/load_balancer.go
Labels: cncf-cla: yes, size/L

#1349 add load balancer attributes
  pkg/model/elbv2/load_balancer.go
Labels: cncf-cla: yes, size/S

#1350 add listener types
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
Labels: cncf-cla: yes, size/L

#1351 Annotations parser
  pkg/annotations/parser.go
  pkg/annotations/parser_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#1355 Add support for bool annotations
  pkg/annotations/parser.go
  pkg/annotations/parser_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1336 Doc - Update annotation.md - Incorrect indentation
  docs/guide/ingress/annotation.md
Labels: cncf-cla: no, needs-ok-to-test, size/S

#1356 add TargetGroup types
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
Labels: cncf-cla: yes, size/L

#1357 add targetGroupBinding resource
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
  pkg/model/elbv2/target_group_binding.go
Labels: cncf-cla: yes, size/M

#1362 add literal string token type
  pkg/model/core/token_types.go
  pkg/model/core/token_types_test.go
Labels: cncf-cla: yes, size/M

#1372 add ResourceFieldStringToken and stack implementation
  pkg/model/core/graph/resource_graph.go
  pkg/model/core/graph/resource_graph_test.go
  pkg/model/core/graph/typological_traversal.go
  pkg/model/core/resource.go
  pkg/model/core/stack.go
  pkg/model/core/token_types.go
  pkg/model/core/token_types_test.go
  pkg/model/ec2/security_group.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
  pkg/model/elbv2/target_group_binding.go
Labels: cncf-cla: yes, size/L

#1373 reconciler and eventhandler framework for service objects
  controllers/service/eventhandlers/service_events.go
  controllers/service/service_controller.go
  go.mod
  main.go
  pkg/equality/ignore_fake_client_populated_fields.go
  pkg/equality/ignore_fake_client_populated_fields_test.go
  pkg/k8s/finalizer.go
  pkg/k8s/finalizer_test.go
  pkg/k8s/utils.go
  pkg/k8s/utils_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#1376 add json model builder
  pkg/deploy/stack_marshaller.go
  pkg/deploy/stack_marshaller_test.go
  pkg/deploy/stack_schema_builder.go
  pkg/deploy/stack_schema_builder_test.go
  pkg/model/core/fake_resource.go
  pkg/model/core/resource.go
  pkg/model/core/token_types.go
  pkg/model/core/token_types_test.go
  pkg/model/ec2/security_group.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
  pkg/model/elbv2/target_group_binding.go
Labels: cncf-cla: yes, size/L

#1377 fix stack_marshaller test case
  pkg/deploy/stack_marshaller.go
  pkg/deploy/stack_marshaller_test.go
Labels: cncf-cla: yes, size/XS

#1361 Model builder for NLB IP mode
  pkg/annotations/constants.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XL
