Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-07, with the labels that each got.

#1310 Fix IAM permission typo in SetWebAcl
  docs/examples/iam-policy.json
Labels: cncf-cla: yes

#1327 update controller-runtime for v2
  Makefile
  PROJECT
  config/default/manager_auth_proxy_patch.yaml
  config/prometheus/monitor.yaml
  go.mod
  go.sum
  main.go
Labels: cncf-cla: yes, size/L

#1315 Add reminder to stickiness annotation to check target group type
  docs/guide/ingress/annotation.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#1330 Add API types for TargetGroupBinding
  PROJECT
  apis/elbv2/v1alpha1/groupversion_info.go
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_targetgroupbindings.yaml
  config/crd/patches/webhook_in_targetgroupbindings.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/targetgroupbinding_editor_role.yaml
  config/rbac/targetgroupbinding_viewer_role.yaml
  config/samples/elbv2_v1alpha1_targetgroupbinding.yaml
  controllers/elbv2/suite_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  go.mod
  go.sum
  main.go
Labels: cncf-cla: yes, size/XL

#1334 initialize aws package
  go.mod
  go.sum
  pkg/aws/cloud.go
  pkg/aws/cloud_config.go
  pkg/aws/metrics/collector.go
  pkg/aws/metrics/collector_test.go
  pkg/aws/metrics/instruments.go
  pkg/aws/retry/custom_retryer.go
  pkg/aws/retry/custom_retryer_test.go
  pkg/aws/services/ec2.go
  pkg/aws/services/ec2_metadata.go
  pkg/aws/services/elbv2.go
  pkg/aws/throttle/condition.go
  pkg/aws/throttle/condition_test.go
  pkg/aws/throttle/config.go
  pkg/aws/throttle/config_test.go
  pkg/aws/throttle/defaults.go
  pkg/aws/throttle/throttler.go
  pkg/aws/throttle/throttler_test.go
  pkg/aws/user_agent.go
  pkg/version/version.go
Labels: cncf-cla: yes, size/XXL

#1299 Adds note about using named ports to Pod Conditions guide
  docs/guide/ingress/pod-conditions.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
