Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-03, with the labels that each got.

#1179 Optimize endpoint reconcile
  internal/alb/tg/targetgroup_group.go
  internal/alb/tg/targetgroup_group_test.go
  internal/ingress/annotations/action/main.go
  internal/ingress/annotations/action/main_test.go
  internal/ingress/annotations/annotations.go
  internal/ingress/controller/handlers/endpoints.go
  internal/ingress/controller/handlers/endpoints_test.go
  mocks/RateLimitingInterface.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1122 Docs: Duplicate port warning.
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#955 Pod readiness gates
  docs/examples/rbac-role.yaml
  docs/guide/ingress/pod-conditions.md
  internal/alb/tg/mock_Controller.go
  internal/alb/tg/mock_TargetsController.go
  internal/alb/tg/targetgroup.go
  internal/alb/tg/targetgroup_group.go
  internal/alb/tg/targetgroup_group_test.go
  internal/alb/tg/targethealth.go
  internal/alb/tg/targethealth_test.go
  internal/alb/tg/targets.go
  internal/alb/tg/targets_test.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/backend/endpoint.go
  internal/ingress/backend/endpoint_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/dummy.go
  internal/ingress/controller/store/mock_Storer.go
  internal/ingress/controller/store/pod.go
  internal/ingress/controller/store/store.go
  mocks/EndpointResolver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1172 rely on node condition instead of EC2 and add cordon node support
  internal/aws/ec2.go
  internal/ingress/annotations/class/main.go
  internal/ingress/backend/endpoint.go
  internal/ingress/backend/endpoint_test.go
  internal/ingress/controller/handlers/node.go
  internal/ingress/controller/store/store.go
  tester/test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1198 support to use regional STS when using iam-for-service-accounts
  internal/aws/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1200 Multiple bug fixes and doc enhancements
  Makefile
  cmd/options.go
  docs/guide/ingress/annotation.md
  internal/alb/lb/loadbalancer.go
  internal/alb/ls/listener.go
  internal/alb/tg/targetgroup_group.go
  internal/alb/tg/targetgroup_group_test.go
  internal/alb/tg/targethealth.go
  internal/alb/tg/targethealth_test.go
  internal/alb/tg/types.go
  internal/ingress/backend/endpoint.go
  internal/ingress/backend/endpoint_test.go
  internal/ingress/controller/handlers/endpoints.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1190 Updated the ingress name.
  docs/guide/ingress/spec.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1201 cut v1.1.6 release
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: approved, cncf-cla: yes, size/M
