Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-06, with the labels that each got.

#1281 Update annotation.md
  docs/guide/ingress/annotation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1246 Update cognito setup.md: typo
  docs/guide/cognito/setup.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1267 Use external-dns image from docker hub & bitnami.
  docs/examples/external-dns.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1270 Add pod conditions to live docs
  mkdocs.yml
Labels: approved, cncf-cla: no, lgtm, ok-to-test, size/XS

#1257 Updates the image version of examples/external-dns.yaml
  docs/examples/external-dns.yaml
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1235 Check for sufficient available free IP space before marking a subnet as useable
  internal/alb/lb/loadbalancer.go
Labels: cncf-cla: no, lgtm, ok-to-test, size/XS

#1253 fix for pod condition type too long
  go.mod
  go.sum
  internal/alb/lb/loadbalancer.go
  internal/alb/tg/targethealth.go
  internal/alb/tg/targethealth_test.go
  internal/ingress/backend/endpoint.go
  internal/ingress/backend/readiness.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1286 bug fix for #1274
  internal/alb/ls/rules.go
  internal/alb/ls/rules_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1287 cut v1.1.8 release
  Makefile
  README.md
  docs/examples/alb-ingress-controller.yaml
  docs/examples/kustomization.yaml
  docs/guide/controller/setup.md
  docs/guide/external-dns/setup.md
  docs/guide/walkthrough/echoserver.md
Labels: cncf-cla: yes
