Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-11, with the labels that each got.

#1605 fix mkdocs rendering
  docs/guide/controller/pod_readiness_gate.md
Labels: cncf-cla: yes, size/XS

#1612 typo fix: alb.ingress.kubernetes.io/tags
  docs/examples/cognito-ingress-template.yaml
Labels: cncf-cla: yes, size/XS

#1617 add version select capability for v2.0 (main branch)
  docs/theme_overrides/assets/javascripts/version-select.js
  docs/theme_overrides/assets/stylesheets/version-select.css
  docs/theme_overrides/main.html
  docs/theme_overrides/partials/header.html
  docs/theme_overrides/partials/version-select.html
  mkdocs.yml
Labels: cncf-cla: yes, size/L

#1616 add version select capability for v1.1(old master branch)
  docs/theme_overrides/assets/javascripts/version-select.js
  docs/theme_overrides/assets/stylesheets/version-select.css
  docs/theme_overrides/main.html
  docs/theme_overrides/partials/header.html
  docs/theme_overrides/partials/version-select.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, size/L

#1607 fix egrep script in walkthrough doc to correctly filter aws-load-balancer-controller
  docs/guide/walkthrough/echo_server.md
Labels: cncf-cla: yes, size/XS

#1619 Remove circular docs link on docs website
  docs/index.md
  mkdocs.yml
Labels: cncf-cla: yes, size/M

#1620 move README.md to top-level and adjust links
  README.md
Labels: cncf-cla: yes, size/XS

#1614 Clarify documentation on ALB sticky session support
  docs/guide/ingress/annotations.md
Labels: cncf-cla: yes, size/XS

#1618 fix: iam policy about registering/deregistering targets
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
Labels: cncf-cla: yes, lgtm, size/S

#1625 Update prerequisites for NLB-IP mode
  .gitignore
  docs/guide/service/nlb_ip_mode.md
Labels: cncf-cla: yes, lgtm, size/XS

#1627 add outpost support and refactor subnetResolver
  main.go
  mocks/networking/mock_subnet_resolver.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_builder_test.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/service/nlb/mock_subnet_resolver.go
Labels: cncf-cla: yes, size/XXL

#1624 Update service annotations documentation
  docs/guide/service/annotations.md
Labels: cncf-cla: yes, size/M

#1631 abstract retry_utils and add retry for listener certificate attachment
  pkg/deploy/ec2/security_group_manager.go
  pkg/deploy/ec2/security_group_manager_test.go
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/listener_utils.go
  pkg/deploy/elbv2/listener_utils_test.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/deploy/elbv2/target_group_manager_test.go
  pkg/runtime/retry_utils.go
  pkg/runtime/retry_utils_test.go
Labels: cncf-cla: yes, size/L

#1635 fix two targetGroup related bug
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/elbv2/target_group_synthesizer_test.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_build_target_group_test.go
  pkg/ingress/model_builder_test.go
Labels: cncf-cla: yes, size/XL

#1637 add event recording and ingress info in error messages
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/eventhandlers/ingress_events.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  main.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_builder.go
  pkg/k8s/events.go
Labels: cncf-cla: yes, size/M

#1641 cut v2.0.1 release
  Makefile
Labels: cncf-cla: yes, size/XS

#1642 add YAML install manifest for v2.0.1
  docs/install/v2_0_1_full.yaml
Labels: cncf-cla: yes, size/XL

#1589 feat: add support to set ProtocolVersion based on annotation values
  docs/guide/ingress/annotations.md
  go.mod
  go.sum
  mocks/aws/services/mock_ec2.go
  pkg/annotations/constants.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/deploy/elbv2/target_group_manager_test.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/target_group.go
Labels: cncf-cla: yes, lgtm, size/L

#1657 Update cert_discovery.md
  docs/guide/ingress/cert_discovery.md
Labels: cncf-cla: yes, size/XS

#1632 Add support for specifying NLB target group attributes
  controllers/service/service_controller.go
  docs/guide/controller/pod_readiness_gate.md
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/ingress/model_build_listener_rules.go
  pkg/service/mock_visitor.go
  pkg/service/model_build_listener.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
  pkg/service/nlb/builder.go
Labels: cncf-cla: yes, lgtm, size/XXL

#1667 Ability to specify subnets for NLB
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder.go
Labels: cncf-cla: yes, size/L

#1666 Add basic GitHub Action for running unit tests + code coverage
  .github/workflows/test.yaml
Labels: cncf-cla: yes, size/S

#1658 Fix documentation: using numerical target ports in services doesn't cause downtime
  docs/guide/upgrade/migrate_v1_v2.md
Labels: cncf-cla: yes, size/S

#1669 Add support for NLB ALPN policy
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_manager_test.go
  pkg/model/elbv2/listener.go
  pkg/service/model_build_listener.go
  pkg/service/model_build_listener_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1670 add ingress class support
  controllers/ingress/group_controller.go
  pkg/config/ingress_config.go
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
  pkg/k8s/events.go
Labels: cncf-cla: yes, size/L

#1674 Allow stringMap annotation values containing equal sign
  pkg/annotations/parser.go
  pkg/annotations/parser_test.go
Labels: cncf-cla: yes, lgtm, size/S

#1676 ignore incorrectly configured Ingresses when building IngressGroup
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
Labels: cncf-cla: yes, size/M

#1675 Update installation guide to refer v2.0.1
  docs/guide/controller/installation.md
  docs/guide/upgrade/migrate_v1_v2.md
Labels: cncf-cla: yes, size/XS

#1678 add service event handler for targetGroupBinding
  controllers/elbv2/eventhandlers/endpoints_test.go
  controllers/elbv2/eventhandlers/service.go
  controllers/elbv2/eventhandlers/service_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  pkg/testutils/client_test_utils.go
  pkg/testutils/event_handler_test_utils.go
Labels: cncf-cla: yes, size/XL

#1580 Adding `endpoints` resource permission
  docs/examples/external-dns.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#1680 docs: make external-dns example to 0.7.2+ working in AWS China
  docs/examples/external-dns.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#1677 Support for IPv6 and NLB
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: cncf-cla: yes, lgtm, size/L

#1290 doc: workaround fix for deploying external-dns
  docs/examples/external-dns.yaml
Labels: cncf-cla: yes, lifecycle/rotten, ok-to-test, size/XS

#1685 add COIP support for ALB on outpost
  docs/guide/ingress/annotations.md
  pkg/annotations/constants.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_test.go
  pkg/model/elbv2/load_balancer.go
Labels: cncf-cla: yes, size/L

#1689 update service.beta.kubernetes.io/aws-load-balancer-healthcheck-port doc
  docs/guide/service/annotations.md
Labels: cncf-cla: yes, size/XS

#1691 typo fix: alb.ingress.kubernetes.io/conditions.${conditions-name}
  docs/guide/ingress/annotations.md
Labels: cncf-cla: yes, size/XS

#1696 add support for default-tags
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  pkg/config/controller_config.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_test.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_managed_sg_test.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_build_target_group_test.go
  pkg/ingress/model_builder.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: cncf-cla: yes, size/XL

#1697 cut v2.1.0 release
  Makefile
  config/controller/kustomization.yaml
  config/rbac/role.yaml
  controllers/ingress/group_controller.go
  docs/guide/controller/configurations.md
  docs/install/v2_1_0_full.yaml
Labels: cncf-cla: yes, size/XL

#1698 Fix the default healthCheck setting for GRPC
  docs/guide/ingress/annotations.md
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_build_target_group_test.go
  pkg/ingress/model_builder.go
Labels: cncf-cla: yes, size/L
