Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2020-09, with the labels that each got.

#1385 V2 ga deploy
  controllers/service/service_controller.go
  mocks/aws/services/mock_elbv2.go
  pkg/algorithm/maps.go
  pkg/algorithm/maps_test.go
  pkg/algorithm/strings.go
  pkg/algorithm/strings_test.go
  pkg/aws/services/elbv2.go
  pkg/aws/throttle/defaults.go
  pkg/deploy/stack_marshaller.go
  pkg/deploy/stack_marshaller_test.go
  pkg/deploy/stack_schema_builder.go
  pkg/deploy/stack_schema_builder_test.go
  pkg/deploy/tagging/provider.go
  pkg/deploy/tagging/provider_test.go
  pkg/deploy/tagging/tags.go
  pkg/deploy/tagging/tags_test.go
  pkg/model/core/stack.go
  pkg/model/core/stack_test.go
  pkg/model/core/token_types_test.go
  pkg/model/elbv2/load_balancer.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, size/XXL

#1383 NLB IP model builder check existing target group
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/service/nlb/mock_visitor.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1387 add ELBV2 tagManager and LoadBalancerAttributeReconciler
  pkg/algorithm/maps.go
  pkg/algorithm/maps_test.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler_test.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/tagging/provider.go
  pkg/deploy/tagging/provider_test.go
  pkg/model/ec2/security_group.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
  pkg/model/elbv2/target_group_binding.go
Labels: cncf-cla: yes, size/XXL

#1388 Add ResourceMeta and LbManager and TgManager
  pkg/deploy/elbv2/load_balancer_attributes_reconciler.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler_test.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
  pkg/deploy/elbv2/target_group_attributes_reconciler.go
  pkg/deploy/elbv2/target_group_attributes_reconciler_test.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/deploy/elbv2/target_group_manager_test.go
  pkg/model/core/fake_resource.go
  pkg/model/core/resource.go
  pkg/model/core/stack_test.go
  pkg/model/ec2/security_group.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/load_balancer.go
  pkg/model/elbv2/target_group.go
  pkg/model/elbv2/target_group_binding.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, size/XXL

#1389 add LB & TG synthesizer
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_synthesizer.go
  pkg/deploy/elbv2/load_balancer_synthesizer_test.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/elbv2/target_group_synthesizer_test.go
Labels: cncf-cla: yes, size/XXL

#1392 add ListenerSynthesizer and deployer
  mocks/aws/services/mock_elbv2.go
  pkg/aws/services/elbv2.go
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_manager_test.go
  pkg/deploy/elbv2/listener_synthesizer.go
  pkg/deploy/elbv2/listener_utils.go
  pkg/deploy/stack_deployer.go
  pkg/equality/elbv2/compare_option_for_actions.go
  pkg/equality/elbv2/compare_option_for_actions_test.go
  pkg/equality/elbv2/compare_option_for_certificates.go
  pkg/equality/elbv2/compare_option_for_certificates_test.go
  pkg/equality/ingore_left_hand_unset.go
  pkg/equality/ingore_left_hand_unset_test.go
Labels: cncf-cla: yes, size/XXL

#1398 Add VPC network subnet resolver
  mocks/aws/services/mock_ec2.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#1394 init runtime & webhook package
  mocks/webhook/mock_mutator.go
  mocks/webhook/mock_validator.go
  pkg/runtime/errors.go
  pkg/runtime/errors_test.go
  pkg/runtime/reconcile.go
  pkg/runtime/reconcile_test.go
  pkg/webhook/context.go
  pkg/webhook/context_test.go
  pkg/webhook/mutating_handler.go
  pkg/webhook/mutating_handler_test.go
  pkg/webhook/mutator.go
  pkg/webhook/validating_handler.go
  pkg/webhook/validating_handler_test.go
  pkg/webhook/validator.go
  scripts/gen_mocks.sh
Labels: cncf-cla: yes, size/XXL

#1400 Add cmdline flags aws-vpc-id and cluster-name
  main.go
  pkg/aws/cloud.go
  pkg/aws/cloud_config.go
  pkg/aws/services/ec2_metadata.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1399 add pod/node/service utility and endpoint resolver
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/backend/endpoint_types.go
  pkg/backend/endpoint_types_test.go
  pkg/backend/endpoint_utils.go
  pkg/deploy/elbv2/listener_manager_test.go
  pkg/k8s/node_utils.go
  pkg/k8s/node_utils_test.go
  pkg/k8s/pod_utils.go
  pkg/k8s/pod_utils_test.go
  pkg/k8s/service_utils.go
  pkg/k8s/service_utils_test.go
Labels: cncf-cla: yes, size/XXL

#1402 deployer & controller for TargetGroupBinding resource
  controllers/elbv2/eventhandlers/endpoints.go
  controllers/elbv2/eventhandlers/node.go
  controllers/elbv2/targetgroupbinding_controller.go
  main.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_synthesizer.go
  pkg/deploy/stack_deployer.go
  pkg/deploy/tagging/provider.go
  pkg/deploy/tagging/provider_test.go
  pkg/model/elbv2/target_group_binding.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/targets_manager.go
  pkg/targetgroupbinding/targets_manager_test.go
  pkg/targetgroupbinding/utils.go
Labels: cncf-cla: yes, size/XL

#1401 Integrate service controller with model deployer
  controllers/service/service_controller.go
  main.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/service/nlb/mock_subnet_resolver.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1408 consider draining targets when reconcile targets
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/targets_manager_types.go
Labels: cncf-cla: yes, size/S

#1406 add listener rule model and deployer
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/listener_rule_synthesizer.go
  pkg/deploy/elbv2/listener_synthesizer.go
  pkg/deploy/elbv2/listener_utils.go
  pkg/deploy/stack_deployer.go
  pkg/equality/elbv2/compare_option_for_rule_conditions.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/listener_rule.go
Labels: cncf-cla: yes, size/XL

#1404 add eni & securityGroup utilities
  mocks/aws/services/mock_ec2.go
  pkg/aws/services/ec2.go
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/k8s/node_utils.go
  pkg/k8s/node_utils_test.go
  pkg/networking/eni_info.go
  pkg/networking/node_eni_info_resolver.go
  pkg/networking/pod_eni_info_resolver.go
  pkg/networking/security_group_info.go
  pkg/networking/security_group_info_test.go
  pkg/networking/security_group_reconciler.go
Labels: cncf-cla: yes, size/XL

#1410 add two equality:FilterField and equality:IgnoreStringSliceOrder
  pkg/equality/filter_field.go
  pkg/equality/filter_field_test.go
  pkg/equality/ignore_string_slice_order.go
  pkg/equality/ignore_string_slice_order_test.go
Labels: cncf-cla: yes, size/L

#1411 add describeSubnetsAsList API
  mocks/aws/services/mock_ec2.go
  pkg/aws/services/ec2.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
Labels: cncf-cla: yes, size/L

#1412 make stringMap annotation parsing error aware
  pkg/annotations/parser.go
  pkg/annotations/parser_test.go
  pkg/service/nlb/builder.go
Labels: cncf-cla: yes, size/L

#1413 add model builder for Ingress loadbalancer
  pkg/annotations/constants.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_builder.go
Labels: cncf-cla: yes, size/L

#1417 add model builder for listener and listenerRules and integrate with ingress controller
  controllers/ingress/group_controller.go
  main.go
  pkg/annotations/constants.go
  pkg/ingress/auth_config_builder.go
  pkg/ingress/config_types.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/model/ec2/security_group.go
  pkg/model/ec2/security_group_ingress.go
  pkg/model/elbv2/listener_rule.go
  pkg/networking/security_group_reconciler.go
  pkg/targetgroupbinding/networking_manager.go
Labels: cncf-cla: yes, size/XXL

#1420 Use service port for targetgroup binding svc reference
  controllers/service/service_controller.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1421 add reconciler for securityGroup rules
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  main.go
  pkg/deploy/ec2/security_group_manager.go
  pkg/deploy/ec2/security_group_synthesizer.go
  pkg/deploy/stack_deployer.go
  pkg/equality/ec2/compare_option_for_ip_permission.go
  pkg/equality/ignore_other_fields.go
  pkg/equality/ignore_other_fields_test.go
  pkg/model/ec2/security_group.go
  pkg/networking/security_group_info.go
  pkg/networking/security_group_info_test.go
  pkg/networking/security_group_manager.go
  pkg/networking/security_group_reconciler.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/XXL

#1422 refactor ingress model builder
  controllers/ingress/group_controller.go
  pkg/annotations/constants.go
  pkg/aws/errors/utils.go
  pkg/deploy/ec2/security_group_manager.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/model/ec2/security_group_ingress.go
  pkg/service/nlb/builder.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/XL

#1425 add install manifest for v2.0.0-rc0
  config/samples/install_v2_0_0_rc0.yaml
Labels: cncf-cla: yes, size/L

#1416 v1 to v2 migration guide
  docs/guide/migration.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1427 add support for pod mutator webhook
  main.go
  pkg/inject/config.go
  pkg/inject/pod_readiness_gate.go
  pkg/inject/pod_readiness_gate_test.go
  webhooks/core/pod_mutator.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#1431 adjust the deployment manifests according to best practices
  Dockerfile
  Makefile
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/controller/controller.yaml
  config/controller/kustomization.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/webhook_in_targetgroupbindings.yaml
  config/default/controller_webhook_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/targetgroupbinding_editor_role.yaml
  config/samples/install_v2_0_0_rc0.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
Labels: cncf-cla: yes, size/XXL

#1423 add networking config to NLB targetgroupbinding
  pkg/ingress/model_build_load_balancer.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/service/nlb/mock_subnet_resolver.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1432 add support for specifying eip allocations
  controllers/service/eventhandlers/service_events.go
  pkg/annotations/constants.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1437 Fix the TargetGroupBinding networking handlings.
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_synthesizer.go
  pkg/ingress/group_loader_test.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/k8s/pod_utils.go
  pkg/k8s/pod_utils_test.go
  pkg/model/elbv2/target_group_binding.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/XXL

#1386 Docs: Ingress pod conditions - fix formatting of bullet list
  docs/guide/ingress/pod-conditions.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1440 Add model/deployer/builder for LoadBalancer Addons(WAF/Shield)
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  main.go
  pkg/annotations/constants.go
  pkg/aws/cloud.go
  pkg/aws/services/shield.go
  pkg/aws/services/wafregional.go
  pkg/aws/services/wafv2.go
  pkg/deploy/shield/protection_manager.go
  pkg/deploy/shield/protection_synthesizer.go
  pkg/deploy/stack_deployer.go
  pkg/deploy/wafregional/web_acl_association_manager.go
  pkg/deploy/wafregional/web_acl_association_synthesizer.go
  pkg/deploy/wafv2/web_acl_association_manager.go
  pkg/deploy/wafv2/web_acl_association_synthesizer.go
  pkg/ingress/model_build_load_balancer_addons.go
  pkg/ingress/model_builder.go
  pkg/model/shield/protection.go
  pkg/model/wafregional/web_acl_association.go
  pkg/model/wafv2/web_acl_association.go
Labels: cncf-cla: yes, size/XXL

#1442 several fix for V2
  main.go
  pkg/ingress/model_build_load_balancer.go
  pkg/model/core/stack_test.go
  pkg/model/shield/protection.go
  pkg/model/wafregional/web_acl_association.go
  pkg/model/wafv2/web_acl_association.go
Labels: cncf-cla: yes, size/S

#1443 cut v2.0.0-rc1 release
  Dockerfile
  Makefile
  config/controller/controller.yaml
  config/controller/kustomization.yaml
  config/samples/install_v2_0_0_rc1.yaml
Labels: cncf-cla: yes, size/L

#1444 add support for targetHealthReadinessGate in tgb
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  config/controller/kustomization.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/pod_mutator_patch.yaml
  main.go
  pkg/inject/config.go
  pkg/inject/pod_readiness_gate.go
  pkg/inject/pod_readiness_gate_test.go
  pkg/k8s/pod_utils.go
  pkg/k8s/pod_utils_test.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/utils.go
  webhooks/core/pod_mutator.go
Labels: cncf-cla: yes, size/XL

#1446 restrict addons to alb only
  pkg/deploy/shield/protection_synthesizer.go
  pkg/deploy/wafregional/web_acl_association_synthesizer.go
  pkg/deploy/wafv2/web_acl_association_synthesizer.go
Labels: cncf-cla: yes, size/S

#1448 dependency handling during resource deletion and fix a bug in TGB
  controllers/elbv2/eventhandlers/endpoints.go
  pkg/deploy/ec2/security_group_manager.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_manager.go
  pkg/targetgroupbinding/resource_manager.go
Labels: cncf-cla: yes, size/L

#1445 Add TargetGroupBinding networking rule for healthcheck port
  controllers/service/service_controller.go
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1449 update rc1 install yaml
  config/samples/install_v2_0_0_rc1.yaml
Labels: cncf-cla: yes, size/M

#1430 user guide for NLB-IP support
  docs/guide/nlb-ip.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#1450 add webhook for TargetGroupBinding and multiple changes to YAMLs
  Makefile
  apis/elbv2/v1alpha1/targetgroupbinding_types.go
  config/controller/iam_for_sa_patch.yaml
  config/controller/kustomization.yaml
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.v1beta1.yaml
  config/webhook/manifests.yaml
  main.go
  webhooks/core/pod_mutator.go
  webhooks/elbv2/targetgroupbinding_mutator.go
  webhooks/elbv2/targetgroupbinding_mutator_test.go
  webhooks/elbv2/targetgroupbinding_validator.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
Labels: cncf-cla: yes, size/XL

#1451 Make the docker container run as non-root & redact OIDC clientID and clientSecret
  Dockerfile
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/listener_test.go
Labels: cncf-cla: yes, size/M

#1453 add sample IAM permission
  docs/install/iam_policy.json
Labels: cncf-cla: yes, size/L

#1458 add cert discovery functionality
  controllers/ingress/group_controller.go
  pkg/aws/cloud.go
  pkg/ingress/cert_discovery.go
  pkg/ingress/cert_discovery_test.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder.go
Labels: cncf-cla: yes, size/L

#1459 fix securityGroup rules reconcile
  pkg/deploy/ec2/security_group_manager.go
  pkg/networking/security_group_manager.go
  pkg/networking/security_group_reconciler.go
  pkg/networking/security_group_reconciler_test.go
  pkg/targetgroupbinding/networking_manager.go
Labels: cncf-cla: yes, size/L

#1457 Change the format for NLB targetgroup naming
  pkg/service/nlb/builder.go
  pkg/service/nlb/builder_test.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1460 add acm client wrapper
  pkg/aws/services/acm.go
Labels: cncf-cla: yes, size/M

#1461 cut v2.0.0-rc2 release
  Makefile
  config/controller/kustomization.yaml
  config/samples/install_v2_0_0_rc2.yaml
Labels: cncf-cla: yes, size/XL

#1462 enable leader election by default
  main.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1464 remove the tag condition for targetGroup actions in IAM policy.
  docs/install/iam_policy.json
Labels: cncf-cla: yes, size/S
