Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-02, with the labels that each got.

#1798 Update documentation for preserve client IP attribute
  docs/guide/service/annotations.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1795 docs: update iam service account creation command
  docs/deploy/installation.md
Labels: cncf-cla: no, lgtm, needs-ok-to-test, size/XS

#1793 docs: update helm install command
  docs/deploy/installation.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS, tide/merge-method-squash

#1800 add mod=readonly
  Dockerfile
Labels: cncf-cla: yes, size/XS

#1802 fix test script by reorder go get command
  scripts/ci_e2e_test.sh
Labels: cncf-cla: yes, size/XS

#1803 add IAM permission that needed by when using with outpost+coIP pool
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
Labels: cncf-cla: yes, size/XS

#1805 docs: Add EKS for fargate configure info
  docs/deploy/installation.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1770 fix typo in nlb ip docs
  docs/guide/service/nlb_ip_mode.md
Labels: cncf-cla: no, needs-ok-to-test, size/XS

#1773 Relax cluster tag requirement on subnets during auto-discovery
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1812 cut v2.1.2 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/install/v2_1_2_full.yaml
Labels: cncf-cla: yes, size/XL

#1815 State supported target-type more clearly in pod readiness gate documentation
  docs/deploy/pod_readiness_gate.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1818 Doc update for NLB-IP prereq
  docs/guide/service/nlb_ip_mode.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1829 Add OWNERS file to the main branch
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#1801 docs: Update v1 to v2 migration guide to include example command for updating SG rules
  docs/deploy/upgrade/migrate_v1_v2.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#1831 Add health check SG rule from VPC if preserve client IP is configured
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  test/framework/utils/poll.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1835 cut v2.1.3 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/install/v2_1_3_full.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1762 Add support for specifying PrivateIpv4Address via annotation
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1772 add support for Ingress pathType
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_build_listener_rules_test.go
  scripts/ci_e2e_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1785 Add support for NodeSelector in TargetGroupBindings
  apis/elbv2/v1beta1/targetgroupbinding_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  controllers/elbv2/eventhandlers/node.go
  docs/guide/targetgroupbinding/targetgroupbinding.md
  pkg/backend/endpoint_utils.go
  pkg/backend/endpoint_utils_test.go
  pkg/targetgroupbinding/resource_manager.go
  webhooks/elbv2/targetgroupbinding_validator.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL, tide/merge-method-squash

#1837 add support for ssl-redirect annotation
  docs/guide/ingress/annotations.md
  pkg/annotations/constants.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_actions_test.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/ingress/ssl_redirect_config.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash

#1844 Change check for remove regacy readiness gate
  pkg/inject/pod_readiness_gate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash
