Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-07, with the labels that each got.

#2114 Add support for AWS SDK override
  Makefile
  scripts/aws_sdk_model_override/cleanup.sh
  scripts/aws_sdk_model_override/setup.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2119 Docs: Document Reconciliation Behaviour When Deletion Protection is Enabled.
  docs/guide/ingress/annotations.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#2120 Clean up extra spaces
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2121 Clean up extra spaces
  docs/examples/external-dns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2125 Restrict subnet auto-discovery to new LB creation only
  controllers/ingress/group_controller.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL, tide/merge-method-squash

#2129 Restrict subnet auto-discovery to new LB creation on service side
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#2130 Add deployment update strategy to aws-load-balancer-controller
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#2140 Update repo name to load-balancer
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#2137 add support for pods supported by IPv4Prefix on ENI
  go.mod
  go.sum
  main.go
  pkg/aws/services/ec2_mocks.go
  pkg/k8s/pod_info.go
  pkg/k8s/pod_info_test.go
  pkg/networking/node_eni_info_resolver.go
  pkg/networking/node_eni_info_resolver_test.go
  pkg/networking/node_info_provider.go
  pkg/networking/node_info_provider_mocks.go
  pkg/networking/node_info_provider_test.go
  pkg/networking/pod_eni_info_resolver.go
  pkg/networking/pod_eni_info_resolver_test.go
  pkg/targetgroupbinding/resource_manager.go
  scripts/gen_mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL, tide/merge-method-squash

#2142 cherry-pick PR-2137(add PD support) into release-2.2
  go.mod
  go.sum
  main.go
  pkg/aws/services/ec2_mocks.go
  pkg/k8s/pod_info.go
  pkg/k8s/pod_info_test.go
  pkg/networking/node_eni_info_resolver.go
  pkg/networking/node_eni_info_resolver_test.go
  pkg/networking/node_info_provider.go
  pkg/networking/node_info_provider_mocks.go
  pkg/networking/node_info_provider_test.go
  pkg/networking/pod_eni_info_resolver.go
  pkg/networking/pod_eni_info_resolver_test.go
  pkg/targetgroupbinding/resource_manager.go
  scripts/gen_mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2147 alpn-policy: Don't require TLS target groups
  docs/guide/service/annotations.md
  pkg/service/model_build_listener.go
  pkg/service/model_build_listener_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#2148 update installation manifests to use v2.2.2
  docs/install/v2_2_2_full.yaml
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash
