Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-10, with the labels that each got.

#2262 Fix typo in service annotations guide
  docs/guide/service/annotations.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2265 Clarify helm installation when using IAM roles or not
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes

#2268 doc: Fix typo in aws-load-balancer-controller README
  helm/aws-load-balancer-controller/README.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2267 Fix documentation edit link to correct repo
  mkdocs.yml
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2189 cert-manager apiversion to v1
  config/certmanager/certificate.yaml
  docs/deploy/installation.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/templates/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2243 doc: Update configuration notes for working with IMDSv2 metadata server
  docs/deploy/installation.md
Labels: needs-ok-to-test, cncf-cla: yes, size/S, tide/merge-method-squash

#2192 Bump pdb apiVersion to v1
  helm/aws-load-balancer-controller/templates/pdb.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, ok-to-test

#2329 make COIP drift check logs drifts instead of error out
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash
