Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-11, with the labels that each got.

#2326 minor changes go.mod and gitignore
  .gitignore
  go.mod
  go.sum
Labels: lgtm, approved, size/L, cncf-cla: yes

#2331 remove ip-address-type dualstack annotation from 2048 example
  docs/examples/2048/2048_full_latest.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2333 Whitespace changes for mkdocs rendering
  docs/guide/service/annotations.md
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2348 Update anchor link of Nodeport from #nodeport to #type-nodeport
  docs/guide/ingress/annotations.md
  docs/guide/service/annotations.md
Labels: lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#1862 Allow TargetGroup endpoints outside the ELB VPC
  main.go
  pkg/aws/cloud.go
  pkg/aws/cloud_config.go
  pkg/networking/vpc_info_provider.go
  pkg/networking/vpc_info_provider_mocks.go
  pkg/networking/vpc_info_provider_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
  scripts/gen_mocks.sh
  test/framework/options.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2342 add feature gate to enable or disable listener rules tagging
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  main.go
  pkg/config/controller_config.go
  pkg/config/feature_gate.go
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/stack_deployer.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2376 NLB Instance mode guide referenced the wrong annotation
  docs/guide/service/nlb.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes, tide/merge-method-squash

#2378 doc: fix iam_policy.json url for v2.3.0
  docs/deploy/installation.md
Labels: cncf-cla: no, needs-ok-to-test, size/XS

#2380 Adding supports for unweighted target group through feature gate and checking SSL policy availability.
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  main.go
  pkg/config/controller_config.go
  pkg/config/feature_gates.go
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/listener_utils.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/stack_deployer.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2375 support IPv6 Pods during AZ detection
  go.mod
  go.sum
  pkg/networking/utils.go
  pkg/networking/utils_test.go
  pkg/networking/vpc_info_provider.go
  pkg/networking/vpc_info_provider_mocks.go
  pkg/networking/vpc_info_provider_test.go
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash
