Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-04, with the labels that each got.

#1912 Add IAM policy for US GovCloud
  docs/install/iam_policy_us-gov.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/L, tide/merge-method-squash

#1919 Adding a note about the preservation of ALB
  docs/deploy/upgrade/migrate_v1_v2.md
Labels: cncf-cla: no, needs-ok-to-test, size/XS

#1904 Highlight the need to tag subnets
  docs/guide/service/nlb_ip_mode.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1898 Additional e2e tests for service
  test/e2e/service/aws_resource_verifier.go
  test/e2e/service/nlb_instance_target.go
  test/e2e/service/nlb_instance_target_test.go
  test/e2e/service/resource_stack.go
  test/framework/resources/aws/load_balancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#1913 add support for IngressClassParams's group settings
  controllers/ingress/eventhandlers/ingress_events.go
  controllers/ingress/group_controller.go
  pkg/ingress/class.go
  pkg/ingress/class_loader.go
  pkg/ingress/class_loader_test.go
  pkg/ingress/finalizer.go
  pkg/ingress/finalizer_test.go
  pkg/ingress/group.go
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_addons.go
  pkg/ingress/model_build_load_balancer_test.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_managed_sg_test.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  webhooks/networking/ingress_validator.go
  webhooks/networking/ingress_validator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1901 gRPC docs
  docs/examples/grpc/grpcserver-deployment.yaml
  docs/examples/grpc/grpcserver-ingress.yaml
  docs/examples/grpc/grpcserver-namespace.yaml
  docs/examples/grpc/grpcserver-service.yaml
  docs/examples/grpc_server.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#1920 add support for local zone
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_us-gov.json
  main.go
  pkg/networking/az_info_provider.go
  pkg/networking/az_info_provider_mocks.go
  pkg/networking/az_info_provider_test.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
  scripts/gen_mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL, tide/merge-method-merge

#1922 adjust mocks generation
  mocks/controller-runtime/client/client_mocks.go
  pkg/aws/services/ec2_mocks.go
  pkg/aws/services/elbv2_mocks.go
  pkg/backend/endpoint_resolver_test.go
  pkg/deploy/ec2/tagging_manager_test.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler_test.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/elbv2/target_group_attributes_reconciler_test.go
  pkg/ingress/cert_discovery_mocks.go
  pkg/ingress/finalizer_test.go
  pkg/ingress/model_builder_test.go
  pkg/k8s/finalizer_mocks.go
  pkg/k8s/pod_info_repo_mocks.go
  pkg/networking/az_info_provider_test.go
  pkg/networking/security_group_manager_mocks.go
  pkg/networking/subnet_resolver_mocks.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder_test.go
  pkg/targetgroupbinding/targets_manager_test.go
  pkg/webhook/mutating_handler_test.go
  pkg/webhook/mutator_mocks.go
  pkg/webhook/validating_handler_test.go
  pkg/webhook/validator_mocks.go
  scripts/gen_mocks.sh
  webhooks/elbv2/targetgroupbinding_mutator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1923 fix flaky throttle test
  pkg/aws/throttle/throttler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1863 Fixed an issue where mergedTLSCerts would be sorted.
  pkg/deploy/elbv2/listener_manager_test.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL, tide/merge-method-squash

#1887 Resource tagging for Listener and Rules
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_us-gov.json
  pkg/deploy/elbv2/listener_manager.go
  pkg/deploy/elbv2/listener_manager_test.go
  pkg/deploy/elbv2/listener_rule_manager.go
  pkg/deploy/elbv2/listener_rule_synthesizer.go
  pkg/deploy/elbv2/listener_synthesizer.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/stack_deployer.go
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_build_listener_rules.go
  pkg/ingress/rule_optimizer.go
  pkg/model/elbv2/listener.go
  pkg/model/elbv2/listener_rule.go
  pkg/service/model_build_listener.go
  pkg/service/model_builder_test.go
  test/e2e/service/aws_resource_verifier.go
  test/e2e/service/nlb_instance_target_test.go
  test/e2e/service/resource_stack.go
  test/framework/resources/aws/load_balancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash

#1944 Fix new tagging ARNs in aws-cn IAM policy
  docs/install/iam_policy_cn.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1943 docs: update Subnet discovery with optional tag
  docs/deploy/subnet_discovery.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS, tide/merge-method-squash
