Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-09, with the labels that each got.

#2198 Support specifying TLS certs/key for webhook in helm chart
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/_helpers.tpl
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2223 Fix typo in README.md
  helm/aws-load-balancer-controller/README.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2205 Support optimized security group rules for ALB
  controllers/ingress/group_controller.go
  main.go
  pkg/annotations/constants.go
  pkg/config/controller_config.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_managed_sg.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/networking/backend_sg_provider.go
  pkg/networking/backend_sg_provider_mocks.go
  pkg/networking/backend_sg_provider_test.go
  scripts/gen_mocks.sh
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#2217 Add code for acquiring region from env; Refactor code to reduce EC2 c…
  pkg/aws/cloud.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2169 EndpointSlice support for IP target groups
  .gitignore
  config/rbac/role.yaml
  controllers/elbv2/eventhandlers/endpointslices.go
  controllers/elbv2/eventhandlers/endpointslices_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  docs/deploy/configurations.md
  main.go
  pkg/aws/cloud.go
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/config/controller_config.go
  pkg/targetgroupbinding/resource_manager.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2227 Add "--region" parameter of eksctl CLI
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes, tide/merge-method-squash

#2171 Create optional serviceAnnotations value in helm chart
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/service.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2236 Add port range restriction for SG
  controllers/ingress/group_controller.go
  main.go
  pkg/config/controller_config.go
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
  pkg/targetgroupbinding/resource_manager.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash, ok-to-test

#2251 add boundary cases and refactor computeRestrictedIngressPermissionsPerSG
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/networking_manager_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#2248 Adds parameter to create IngressClass Resource
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/ingressclass.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test
