Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2021-12, with the labels that each got.

#2332 Add support for NLB IPv6 targets groups
  controllers/service/service_controller.go
  main.go
  pkg/networking/vpc_resolver.go
  pkg/networking/vpc_resolver_mocks.go
  pkg/networking/vpc_resolver_test.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
  scripts/gen_mocks.sh
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#2374 doc update for subnet auto-discovery
  docs/deploy/subnet_discovery.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, size/S

#2385 Minimalist IAM permissions for TargetGroupBinding [documentation]
  docs/deploy/installation.md
Labels: needs-ok-to-test, cncf-cla: yes, size/M

#2387 call subnet auto discovery when lb scheme changes
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_builder_test.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2394 webhook server use TLS 1.2 as minimum version
  main.go
  pkg/config/runtime_config.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2397 Fix listener utils error handling
  pkg/deploy/elbv2/listener_utils.go
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2390 doc improvement for IAM policy restriction
  docs/deploy/installation.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2356 chore: clarify how to get internal NLB
  docs/guide/service/annotations.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2324 implement dnsPolicy in aws-load-balancer-controller chart
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2391 Set a namespace on the helm PodDisruptionBudget template
  helm/aws-load-balancer-controller/templates/pdb.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, ok-to-test

#2400 cut v2.3.1 release
  Dockerfile
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2401 Update golang to 1.17
  Dockerfile
  go.mod
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2408 cache AWS shield subscription state for 2 hour
  pkg/aws/services/shield.go
  pkg/aws/services/shield_mocks.go
  pkg/deploy/shield/protection_manager.go
  pkg/deploy/shield/protection_manager_test.go
  pkg/deploy/stack_deployer.go
  scripts/gen_mocks.sh
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#2407 Enable setting custom objectSelector for webhook
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2416 Typo
  pkg/ingress/cert_discovery.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2418 Add workflow to auto sync helm chart to eks-charts
  scripts/sync-to-eks-charts.sh
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2246 e2e test helper script
  test/e2e/run-canary-test.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2429 updated Ingress API version in Documentation example
  docs/guide/ingress/spec.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes
