Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-01, with the labels that each got.

#2435 e2e: Use Helm chart from the commit
  scripts/ci_e2e_test.sh
  test/e2e/ingress/multi_path_backend_test.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/framework/controller/constants.go
  test/framework/controller/installation_manager.go
  test/framework/framework.go
  test/framework/helm/release_manager.go
  test/framework/options.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2445 Add a separate example for dualstack ALB
  docs/examples/2048/2048_full_dualstack.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2442 helm: Create IngressClass by default
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2443 helm: Remove unnecessary admissionregistration.k8s.io/v1beta1
  helm/aws-load-balancer-controller/templates/webhook.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2425 Add default tags to backend SG
  docs/deploy/configurations.md
  main.go
  pkg/config/controller_config.go
  pkg/networking/backend_sg_provider.go
  pkg/networking/backend_sg_provider_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2447 Format AWS policy JSON document for consistency.
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_us-gov.json
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2452 Upgrade echoserver to 2.5
  docs/examples/echoservice/echoserver-deployment.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2450 log enhacement for subnet auto discovery
  pkg/networking/subnet_resolver.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, ok-to-test

#2454 check invalid TG ARN when deleting TGB
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  pkg/targetgroupbinding/resource_manager.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2436 Fetch aws-load-balancer-controller logs before deleting
  test/e2e/run-canary-test.sh
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes, tide/merge-method-squash
