Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-07, with the labels that each got.

#2714 docs: update versions in instructions to match official AWS docs
  docs/deploy/installation.md
Labels: kind/documentation, needs-ok-to-test, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2700 Add docs for example of gRPC health check success codes
  docs/guide/ingress/annotations.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2725 Clarify that ip-mode can be NodePort or ClusterIp
  docs/guide/ingress/annotations.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#2626 Fix Dockerfile go dependency caching
  Dockerfile
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2649 Do not set caBundle for webhooks if CertManager is used
  helm/aws-load-balancer-controller/templates/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2659 Update default cluster version for e2e tests
  scripts/ci_e2e_test.sh
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2723 e2e test changes to support china regions
  scripts/run-e2e-test.sh
  test/e2e/ingress/multi_path_backend.go
  test/framework/manifest/fixed_response_service_builder.go
  test/framework/utils/constants.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2732 fix failures during upgrade when using the default provided IngressClass and IngressClassParam
  helm/aws-load-balancer-controller/templates/ingressclass.yaml
  helm/aws-load-balancer-controller/templates/ingressclassparams.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2739 Enhance client side throttling information
  docs/deploy/configurations.md
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2742 Update go pkg dependencies
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2724 Helm: Add field for Webhook namespace selector
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2743 use a dedicated config to disable default pod affinity
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2745 add HELM support for aws-api-throttle
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2746 bump chart version to 1.4.3
  helm/aws-load-balancer-controller/Chart.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash
