Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-08, with the labels that each got.

#2704 revise install guide
  docs/deploy/installation.md
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2680 add docs for NLB TLS termination
  docs/guide/use_cases/nlb_tls_termination/cert_arn.png
  docs/guide/use_cases/nlb_tls_termination/dns_record.png
  docs/guide/use_cases/nlb_tls_termination/fig.jpg
  docs/guide/use_cases/nlb_tls_termination/index.md
  mkdocs.yml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2750 enhance handling for InvalidIngressClass case
  pkg/ingress/group_loader.go
  pkg/ingress/group_loader_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2753 cut v2.4.3 release
  Dockerfile
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2773 Fix documentation typo s/Amzon/Amazon/
  docs/guide/ingress/annotations.md
Labels: lgtm, needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2780 refine docs about NLB
  docs/guide/service/annotations.md
  docs/guide/service/nlb.md
  mkdocs.yml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2776 Allow configuring the controller feature gates in helm chart
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#2770 Allow configuring the actual cluster DNS domain for the TLS certificate
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/_helpers.tpl
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test
