Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-12, with the labels that each got.

#2899 fix: health check timeout for services/NLB
  docs/deploy/configurations.md
  pkg/config/feature_gates.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2907 Use public ECR repository by default
  Makefile
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/ci/values.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2935 move test images to ecr public
  test/framework/utils/constants.go
Labels: size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2937 Update installation.md (nit)
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2943 use multi-arch image for service e2e test
  test/e2e/service/nlb_instance_target.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2941 fix: typo in synthesizer test
  pkg/deploy/elbv2/load_balancer_synthesizer_test.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2950 docs: make external-dns optional in echoserver walkthrough
  docs/examples/echo_server.md
  docs/examples/echoservice/echoserver-ingress.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2947 fix typos in doc about self managed lb
  docs/guide/use_cases/self_managed_lb/index.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2953 update controller-gen to v0.11.1
  Makefile
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash
