Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-09, with the labels that each got.

#2765 add guide on using a self managed (or existing) load balancer
  docs/guide/use_cases/self_managed_lb/index.md
  mkdocs.yml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2740 Sticky weighted routing
  docs/guide/ingress/annotations.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2783 fix error handling of load balancer deletion
  pkg/deploy/elbv2/load_balancer_synthesizer.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2790 add support for configure static IPv6 addresses on NLB
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/model/elbv2/load_balancer.go
  pkg/networking/utils.go
  pkg/networking/utils_test.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#2795 Fix webhook port value
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes

#2798 Fix typo
  docs/guide/ingress/annotations.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes

#2808 upgrade to golang 1.18.6
  Dockerfile
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2810 configure default client-side throttle for ELBv2 APIs
  docs/deploy/configurations.md
  pkg/aws/throttle/defaults.go
  pkg/ingress/group_loader.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2815 cut v2.4.4 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2817 Fix misspelling
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes

#2816 Fix value name
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test
