Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-11, with the labels that each got.

#2871 upgrade golang to v1.9.3
  .github/workflows/test.yaml
  Dockerfile
  go.mod
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2872 maintain helm chart test.yaml file
  helm/aws-load-balancer-controller/.helmignore
  helm/aws-load-balancer-controller/test.yaml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2876 Fix typo of a comment in pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, ok-to-test

#2877 Fix to use a code block in the guide of ingress annotations
  docs/guide/ingress/annotations.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes

#2878 cut v2.4.5 release
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2868 Documentation update to warn of Access Control bypass when conversion from IPv4 to IPv6 on NLBs
  docs/guide/service/annotations.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2880 Fix consistency of version references in documentation, etc.
  .github/workflows/test.yaml
  .gitignore
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  hack/set-version
  hack/verify-versions.sh
  version-stable.txt
  version.txt
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2879 Stop restricting branches for unit test action
  .github/workflows/test.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2889 update filename from the set-version script
  docs/deploy/installation.md
  hack/set-version
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2887 update go packages and dependencies
  go.mod
  go.sum
  pkg/aws/services/ec2_mocks.go
  scripts/ci_e2e_test.sh
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#2895 update external dns manifest and docs
  docs/examples/echo_server.md
  docs/examples/external-dns.yaml
  docs/guide/integrations/external_dns.md
  mkdocs.yml
Labels: lgtm, approved, cncf-cla: yes, tide/merge-method-squash
