Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-02, with the labels that each got.

#2335 feat(chart): add servicemonitor
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/_helpers.tpl
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/templates/service.yaml
  helm/aws-load-balancer-controller/templates/servicemonitor.yaml
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2480 Merge tags from alb.ingress.kubernetes.io/tags
  docs/guide/ingress/annotations.md
  pkg/ingress/model_build_tags.go
  pkg/ingress/model_build_tags_test.go
  test/e2e/ingress/multi_path_backend.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2478 Adding support of ingressClassParams in helm charts
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/_helpers.tpl
  helm/aws-load-balancer-controller/templates/ingressclass.yaml
  helm/aws-load-balancer-controller/templates/ingressclassparams.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2482 fix typo in annotations doc
  docs/guide/ingress/annotations.md
  docs/guide/service/annotations.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2486 add documentation for manage-backend-security-group-rules
  docs/guide/ingress/annotations.md
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2489 add support for loadBalancerClass
  apis/elbv2/v1alpha1/zz_generated.deepcopy.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  controllers/service/eventhandlers/service_events.go
  controllers/service/service_controller.go
  pkg/config/controller_config.go
  pkg/config/feature_gates.go
  pkg/config/service_config.go
  pkg/k8s/events.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
  pkg/service/service_utils.go
  pkg/service/service_utils_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#2481 Add an option to disable SG rules management for NLB
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2503 Helm chart for v2.4.0 release
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2508 change IngressClassParams default name to alb
  helm/aws-load-balancer-controller/templates/_helpers.tpl
  helm/aws-load-balancer-controller/templates/ingressclassparams.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2506 doc updates for v2.4.0
  docs/deploy/configurations.md
  docs/deploy/installation.md
  docs/examples/echo_server.md
  docs/examples/external-dns.yaml
  docs/guide/service/annotations.md
  docs/guide/service/nlb.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2507 cut v2.4.0 release
  Dockerfile
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2516 Make e2e LB name test work with clusters that have . in the name
  test/e2e/ingress/vanilla_ingress_test.go
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2518 typo error
  docs/guide/ingress/annotations.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes
