Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2022-10, with the labels that each got.

#2453 Query IMDS over IPv6 if no IPv4 interface address
  pkg/aws/cloud.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2831 alpn-policy accept only string and not alpn-policy
  docs/guide/service/annotations.md
Labels: cncf-cla: no, needs-ok-to-test, size/XS

#2833 upgrade controller-runtime to v0.9.7
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2835 Upgrade ginkgo version; address go fmt
  controllers/ingress/eventhandlers/ingress_class_params_events.go
  go.mod
  go.sum
  pkg/equality/ingore_left_hand_unset.go
  pkg/ingress/group.go
  pkg/ingress/model_build_tags.go
  pkg/ingress/rule_optimizer.go
  pkg/k8s/pod_info_repo.go
  webhooks/elbv2/targetgroupbinding_validator.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2824 Retrieve VPC ID from EC2 instance the controller is running on if possible
  pkg/aws/cloud.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2839 Install correct ginkgo version and pass no color to script
  go.mod
  go.sum
  scripts/ci_e2e_test.sh
  scripts/run-e2e-test.sh
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test
