Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-03, with the labels that each got.

#3078 enable EndpointsFailOpen by default
  docs/deploy/configurations.md
  pkg/config/feature_gates.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3025 Add SSLPolicy field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/service/model_build_listener_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3089 Add InboundCIDRs field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder_test.go
  webhooks/elbv2/ingressclassparams_validator.go
  webhooks/elbv2/ingressclassparams_validator_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2988 docs: add a new page about security groups management
  docs/deploy/security_groups.md
  mkdocs.yml
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3067 Added ssl-ports validation in case unused ports are introduced in the aws-load-balancer-ssl-ports annotation
  pkg/service/model_build_listener.go
  pkg/service/model_build_listener_test.go
  test/e2e/service/nlb_ip_target_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3114 Update module dependencies
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3115 Update ko to v0.13.0
  hack/install-ko.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2925 Add webhook for claiming load balancers without LoadBalancerClass
  main.go
  webhooks/core/service_mutator.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3119 add test coverage for endPointSlices
  test/e2e/ingress/multi_path_backend_test.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/framework/controller/installation_manager.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#3121 Added alternate policies and other edits.
  docs/deploy/installation.md
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3120 update eksctl and default eks versions
  scripts/ci_e2e_test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3123 update iam policy version to 2.4.7
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes, tide/merge-method-squash

#3122 cherry pick #3121 to branch release-2.4 and update the version to 2.4.7
  docs/deploy/installation.md
Labels: needs-ok-to-test, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3127 fix installation.md rendering
  docs/deploy/installation.md
Labels: needs-ok-to-test, cncf-cla: yes, size/S, tide/merge-method-squash
