Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-06, with the labels that each got.

#3221 refactor e2e framework and add env PROD_IMAGE_REGISTRY to test script
  scripts/run-e2e-test.sh
  test/e2e/ingress/multi_path_backend.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/e2e/service/nlb_instance_target.go
  test/e2e/service/nlb_ip_target_test.go
  test/framework/manifest/fixed_response_service_builder.go
  test/framework/options.go
  test/framework/utils/constants.go
  test/framework/utils/image.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3226 fix typo in test script
  scripts/run-e2e-test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3228 chore: Added dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3239 Update dependency and base image
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3253 update to go 1.20.5
  Makefile
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3255 cut v2.5.3 release
  .ko.yaml
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash
