Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-01, with the labels that each got.

#2954 docs: fix gRPCServer example
  docs/examples/grpc/grpcserver-ingress.yaml
  docs/examples/grpc_server.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2959 Update index.md
  docs/guide/use_cases/self_managed_lb/index.md
Labels: needs-ok-to-test, size/XS, cncf-cla: yes

#2960 Update eksctl and eks default versions for e2e tests
  scripts/ci_e2e_test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2961 docs: update contibutor docs
  CONTRIBUTING.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2962 Replace "SSL" with "TLS" where possible in documentation
  docs/examples/cognito-ingress-template.yaml
  docs/guide/ingress/annotations.md
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#2967 Ability to reconfigure NLB target group health check
  docs/deploy/configurations.md
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/config/feature_gates.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/elbv2/target_group_synthesizer_test.go
  pkg/deploy/stack_deployer.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2911 add example of blue/green deployment
  docs/guide/use_cases/blue_green/index.md
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2968 cut v2.4.6 release
  Makefile
  config/controller/kustomization.yaml
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
  config/rbac/role.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  hack/set-version
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/crds/crds.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#2970 cut v2.4.6 release
  helm/aws-load-balancer-controller/Chart.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2881 Add GitHub Action for tagging releases and creating release branches
  .github/workflows/tag-release.yml
  docs/release.md
  hack/tag-release.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2840 Add --default-target-type flag
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  pkg/config/controller_config.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
  pkg/service/service_utils_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2987 Replace inet.af/netaddr with net/netip
  go.mod
  go.sum
  pkg/networking/utils.go
  pkg/networking/utils_test.go
  pkg/targetgroupbinding/resource_manager.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#2993 Start migration to leases for leader election
  config/rbac/leader_election_role.yaml
  helm/aws-load-balancer-controller/templates/rbac.yaml
  pkg/config/runtime_config.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2955 Build image with ko
  .ko.yaml
  Dockerfile
  Makefile
  hack/install-ko.sh
  helm/aws-load-balancer-controller/templates/deployment.yaml
  scripts/ci_e2e_test.sh
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2996 Fix typo in 'Subnet Discovery'
  docs/deploy/subnet_discovery.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2994 Update module dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2990 helm: add "defaultTargetType" values setting
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#2999 Add johngmyers as reviewer
  OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2998 Update module dependencies
  controllers/elbv2/eventhandlers/endpoints_test.go
  controllers/elbv2/eventhandlers/endpointslices_test.go
  controllers/elbv2/eventhandlers/service_test.go
  controllers/ingress/group_controller.go
  go.mod
  go.sum
  mocks/controller-runtime/client/client_mocks.go
  pkg/backend/endpoint_resolver_test.go
  pkg/backend/endpoint_utils_test.go
  pkg/deploy/ec2/tagging_manager_test.go
  pkg/deploy/elbv2/load_balancer_attributes_reconciler_test.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/elbv2/target_group_attributes_reconciler_test.go
  pkg/deploy/shield/protection_manager_test.go
  pkg/ingress/model_builder_test.go
  pkg/ingress/reference_indexer_test.go
  pkg/ingress/rule_optimizer_test.go
  pkg/inject/pod_readiness_gate_test.go
  pkg/k8s/finalizer_test.go
  pkg/k8s/secrets_manager_test.go
  pkg/networking/az_info_provider_test.go
  pkg/networking/backend_sg_provider_test.go
  pkg/networking/node_eni_info_resolver_test.go
  pkg/networking/node_info_provider_test.go
  pkg/networking/pod_eni_info_resolver_test.go
  pkg/networking/subnet_resolver_test.go
  pkg/networking/vpc_info_provider_test.go
  pkg/runtime/concise_logger.go
  pkg/runtime/reconcile_test.go
  pkg/targetgroupbinding/resource_manager_test.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/framework/framework.go
  test/framework/utils/log.go
  webhooks/elbv2/targetgroupbinding_mutator_test.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
  webhooks/networking/ingress_validator_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash
