Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-10, with the labels that each got.

#3422 update container name in prow script
  scripts/run-e2e-test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes

#3423 Master - Update v1 README.md to correct migrate text to current project name
  README.md
Labels: kind/documentation, lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#3426 doc updates
  docs/deploy/installation.md
  docs/guide/ingress/ingress_class.md
  docs/index.md
Labels: lgtm, cncf-cla: yes, size/M

#3429 Stricter dependency/security review
  .github/workflows/deps.yml
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3342 Expose ingress configuration options for missing backends
  config/webhook/manifests.yaml
  controllers/ingress/group_controller.go
  docs/deploy/configurations.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  pkg/config/ingress_config.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/model_builder_test.go
  pkg/ingress/reference_indexer_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#3419 feat: resolve health check port name for NLB
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/targetgroupbinding/networking_manager.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test, tide/merge-method-merge

#3432 fix test flow failure
  config/webhook/manifests.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes

#3436 Cherry-picked commits for patch release v2.6.2
  .github/workflows/deps.yml
  Makefile
  controllers/ingress/group_controller.go
  docs/deploy/configurations.md
  docs/deploy/installation.md
  docs/guide/ingress/ingress_class.md
  docs/index.md
  go.mod
  go.sum
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  pkg/config/ingress_config.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/model_builder_test.go
  pkg/ingress/reference_indexer_test.go
  pkg/k8s/events.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/targetgroupbinding/networking_manager.go
  pkg/targetgroupbinding/resource_manager.go
  scripts/ci_e2e_test.sh
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#3425 Revise page on security groups
  docs/deploy/security_groups.md
  docs/guide/use_cases/frontend_sg/index.md
  mkdocs.yml
Labels: lgtm, approved, size/L, cncf-cla: yes

#3453 cut v2.6.2 release
  .ko.yaml
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#3416 enable ingress instance e2e test for ipv6
  scripts/run-e2e-test.sh
  test/e2e/ingress/multi_path_backend_test.go
  test/e2e/ingress/vanilla_ingress_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3457 Updating helm chart version
  helm/aws-load-balancer-controller/Chart.yaml
Labels: lgtm, needs-ok-to-test, size/XS, cncf-cla: yes
