Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-05, with the labels that each got.

#3186 Support AWS RGT APIs with feature flag
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  go.mod
  go.sum
  pkg/aws/services/rgt.go
  pkg/config/feature_gates.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/stack_deployer.go
Labels: lgtm, needs-ok-to-test, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3193 cherry-pick: Support AWS RGT APIs with feature flag (#3186)
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  go.mod
  go.sum
  pkg/aws/services/rgt.go
  pkg/config/feature_gates.go
  pkg/deploy/elbv2/tagging_manager.go
  pkg/deploy/elbv2/tagging_manager_test.go
  pkg/deploy/stack_deployer.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3196 check both sdkLS and resLS sslpolicy for nil
  pkg/deploy/elbv2/listener_manager.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3202 Fix typo in mkdocs.yml file
  mkdocs.yml
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3205 cut v2.5.2 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3206 update go.sum
  go.sum
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3211 refactor e2e tests
  scripts/run-e2e-test.sh
  test/e2e/ingress/multi_path_backend.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/e2e/service/nlb_instance_target.go
  test/e2e/service/nlb_ip_target_test.go
  test/framework/manifest/fixed_response_service_builder.go
  test/framework/utils/constants.go
  test/framework/utils/image.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3213 add TEST_IMAGE_REGISTRY to e2e script
  scripts/run-e2e-test.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#3189 Explicitly setting CertManager APIVersion to V1
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#3219 Fix formatting
  docs/examples/echo_server.md
Labels: lgtm, needs-ok-to-test, size/XS, approved, cncf-cla: yes
