Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-02, with the labels that each got.

#3007 Verify generated files are up to date in merge check
  Makefile
  hack/verify-generate.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2945 Add subnets field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  config/webhook/manifests.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
  main.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_test.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_mocks.go
  pkg/networking/subnet_resolver_test.go
  webhooks/elbv2/ingressclassparams_validator.go
  webhooks/elbv2/ingressclassparams_validator_test.go
  webhooks/elbv2/targetgroupbinding_validator.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#2963 fix: check default ingclass when ingclass is nill
  pkg/ingress/class_loader.go
  pkg/ingress/class_loader_test.go
  pkg/ingress/group_loader.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3028 Remove constrains of multiple TLS on certificate auto-discovery
  pkg/ingress/cert_discovery.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3024 Refactor model builder test
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#3022 Verify CRDs are up to date in merge check
  Makefile
  hack/verify-crds.sh
  helm/aws-load-balancer-controller/crds/crds.yaml
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#3066 Fix conciseLogger's incorrect call to variadic func
  pkg/runtime/concise_logger.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#2735 Validate Ingress condition annotations
  pkg/ingress/config_types.go
  pkg/ingress/enhanced_backend_builder.go
  webhooks/networking/ingress_validator.go
  webhooks/networking/ingress_validator_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3072 update to discovery.k8s.io/v1
  controllers/elbv2/eventhandlers/endpointslices.go
  controllers/elbv2/eventhandlers/endpointslices_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  go.mod
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/backend/endpoint_types.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3073 update to discovery.k8s.io/v1
  Makefile
  controllers/elbv2/eventhandlers/endpointslices.go
  controllers/elbv2/eventhandlers/endpointslices_test.go
  controllers/elbv2/targetgroupbinding_controller.go
  pkg/backend/endpoint_resolver.go
  pkg/backend/endpoint_resolver_test.go
  pkg/backend/endpoint_types.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3068 update recommended IAM policy template
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_us-gov.json
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash, ok-to-test

#3074 cut v2.4.7 release
  Dockerfile
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3075 Update the default container base image
  .ko.yaml
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash
