Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-07, with the labels that each got.

#3280 fix the bug that evenhanlder ignores the update per sync-period
  controllers/ingress/eventhandlers/ingress_events.go
  controllers/service/eventhandlers/service_events.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3274 update protobuf to the latest version
  go.mod
  go.sum
Labels: lgtm, size/XS, approved, cncf-cla: yes

#3281 doc enhancement for waf addons and reconciliation
  docs/deploy/configurations.md
  docs/guide/ingress/annotations.md
  docs/how-it-works.md
  helm/aws-load-balancer-controller/values.yaml
  pkg/config/runtime_config.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3282 cut v2.5.4 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M

#3267 fix: typo in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3257 Docs: Fix typo in `nlb.md`.
  docs/guide/service/nlb.md
Labels: lgtm, size/XS, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3289 Add note about keeping OWNERS in sync
  OWNERS
Labels: size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3180 Doc: Add warning in doc for ServiceMutatorWebhook
  docs/deploy/installation.md
Labels: needs-ok-to-test, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3256 test/framework: replace deprecated ioutil.ReadAll
  test/framework/http/response.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3292 Provide better explanation of failure to find a subnet
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3271 Bump github.com/aws/aws-sdk-go from 1.44.184 to 1.44.294
  go.mod
  go.sum
  pkg/aws/services/ec2_mocks.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash
