Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2023-09, with the labels that each got.

#3373 remove unnecessary patch requests when PodReadinessGate is enabled.
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
Labels: area/performance, lgtm, approved, size/L, cncf-cla: yes

#3380 remove unnecessary patch requests
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#3384 update docs for v2.6.1 release
  .ko.yaml
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M

#3387 remove unnecessary cleanup in prow script
  scripts/run-e2e-test.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3398 update file paths in prow script for adc regions
  scripts/run-e2e-test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes

#3392 update ci e2e script for cert IDs
  scripts/ci_e2e_test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#3407 enable nlb-instance e2e tests for ipv6
  test/e2e/service/nlb_instance_target_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3406 update prow script
  scripts/run-e2e-test.sh
  test/prow/v2_6_0_ingclass.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash
