Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2024-08, with the labels that each got.

#3798 bump up go to 1.22.5
  .go-version
Labels: lgtm, size/XS, approved, cncf-cla: yes

#3800 keep LB addons' settings unchanged unless explicitly specified
  docs/guide/ingress/annotations.md
  pkg/deploy/shield/protection_manager_mocks.go
  pkg/deploy/shield/protection_synthesizer.go
  pkg/deploy/shield/protection_synthesizer_test.go
  pkg/deploy/wafregional/web_acl_association_manager_mocks.go
  pkg/deploy/wafregional/web_acl_association_synthesizer.go
  pkg/deploy/wafregional/web_acl_association_synthesizer_test.go
  pkg/deploy/wafv2/web_acl_association_manager_mocks.go
  pkg/deploy/wafv2/web_acl_association_synthesizer.go
  pkg/deploy/wafv2/web_acl_association_synthesizer_test.go
  pkg/ingress/model_build_load_balancer_addons.go
  pkg/ingress/model_build_load_balancer_addons_test.go
  pkg/model/shield/protection.go
  scripts/gen_mocks.sh
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#3801 cherry-pick commits from main into release-2.8
  .go-version
  docs/guide/ingress/annotations.md
  pkg/deploy/shield/protection_manager_mocks.go
  pkg/deploy/shield/protection_synthesizer.go
  pkg/deploy/shield/protection_synthesizer_test.go
  pkg/deploy/wafregional/web_acl_association_manager_mocks.go
  pkg/deploy/wafregional/web_acl_association_synthesizer.go
  pkg/deploy/wafregional/web_acl_association_synthesizer_test.go
  pkg/deploy/wafv2/web_acl_association_manager_mocks.go
  pkg/deploy/wafv2/web_acl_association_synthesizer.go
  pkg/deploy/wafv2/web_acl_association_synthesizer_test.go
  pkg/ingress/model_build_load_balancer_addons.go
  pkg/ingress/model_build_load_balancer_addons_test.go
  pkg/model/shield/protection.go
  scripts/gen_mocks.sh
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#3803 update mkdocs dependencies
  Pipfile
  Pipfile.lock
  mkdocs.yml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3770 Move envFrom to the correct position and update example
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#3775 fixup(sg-resolver): Allow multiple SGs with the same Name tag
  pkg/algorithm/slices.go
  pkg/algorithm/slices_test.go
  pkg/networking/security_group_resolver.go
  pkg/networking/security_group_resolver_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test
