Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-03, with the labels that each got.

#4081 [feat] add ipv4 ipam support for alb
  apis/elbv2/v1beta1/ingressclassparams_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/annotations.md
  docs/guide/ingress/ingress_class.md
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_iso.json
  docs/install/iam_policy_isob.json
  docs/install/iam_policy_isoe.json
  docs/install/iam_policy_isof.json
  docs/install/iam_policy_us-gov.json
  go.mod
  go.sum
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/annotations/constants.go
  pkg/aws/services/elbv2.go
  pkg/aws/services/elbv2_mocks.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
  pkg/ingress/model_build_ipam.go
  pkg/ingress/model_build_ipam_test.go
  pkg/ingress/model_build_load_balancer.go
  pkg/model/elbv2/load_balancer.go
Labels: approved, size/XXL, cncf-cla: yes

#3860 Add PrefixListsIDs field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4079 Added support for setting Proxy protocol per target group based on ServicePort
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4095 [bug fix] handle ram shared VPCs for cross account tgb
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/targetgroupbinding/resource_manager.go
  pkg/targetgroupbinding/resource_manager_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4078 docs: added example for multiple certificates to Service annotation
  docs/guide/service/annotations.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/S

#4101 fix(docs): update broken link to TargetGroupBinding CRD page
  docs/guide/use_cases/self_managed_lb/index.md
Labels: lgtm, needs-ok-to-test, size/XS, approved, cncf-cla: yes

#4108 update helm to upgrade containerd
  go.mod
  go.sum
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4056 add prometheus metrics
  controllers/elbv2/targetgroupbinding_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/guide/metrics/prometheus/index.md
  main.go
  mkdocs.yml
  pkg/deploy/stack_deployer.go
  pkg/error/error_with_metrics.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/metrics/aws/collector.go
  pkg/metrics/aws/instruments.go
  pkg/metrics/lbc/collector.go
  pkg/metrics/lbc/instruments.go
  pkg/metrics/lbc/mockcollector.go
  pkg/metrics/util/reconcile_counter.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
  pkg/targetgroupbinding/resource_manager.go
  webhooks/core/pod_mutator.go
  webhooks/core/service_mutator.go
  webhooks/elbv2/ingressclassparams_validator.go
  webhooks/elbv2/ingressclassparams_validator_test.go
  webhooks/elbv2/targetgroupbinding_mutator.go
  webhooks/elbv2/targetgroupbinding_mutator_test.go
  webhooks/elbv2/targetgroupbinding_validator.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
  webhooks/networking/ingress_validator.go
  webhooks/networking/ingress_validator_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4109 Enhance subnet discovery
  docs/deploy/subnet_discovery.md
  docs/install/iam_policy.json
  docs/install/iam_policy_cn.json
  docs/install/iam_policy_iso.json
  docs/install/iam_policy_isob.json
  docs/install/iam_policy_isoe.json
  docs/install/iam_policy_isof.json
  docs/install/iam_policy_us-gov.json
  main.go
  pkg/aws/services/ec2.go
  pkg/aws/services/ec2_mocks.go
  pkg/config/feature_gates.go
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_test.go
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_mocks.go
  pkg/networking/subnet_resolver_test.go
  pkg/service/model_build_load_balancer.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4105 Allow override of Certificate resource fields for duration of webhook certs
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#4114 fix bug(introduced by #4109) in subnet resolver
  pkg/networking/subnet_resolver.go
  pkg/networking/subnet_resolver_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4104 Update Go to version 1.24.1, update base image to AL2023
  .go-version
  Makefile
  go.mod
  pkg/networking/utils.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test
