Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-05, with the labels that each got.

#4161 [Rebase + Bugfixes] Add support for TCP_UDP Listeners
  .gitignore
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  docs/guide/service/annotations.md
  pkg/annotations/constants.go
  pkg/config/feature_gates.go
  pkg/ingress/model_build_target_group.go
  pkg/service/model_build_listener.go
  pkg/service/model_build_listener_test.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4157 bug: fix misformated crd url in CRD cleanup
  scripts/run-e2e-test.sh
Labels: lgtm, needs-ok-to-test, size/XS, approved, cncf-cla: yes

#4029 Add `targetType` field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_target_group.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3898 add missing targets field to de/registered targets log messages
  pkg/targetgroupbinding/targets_manager.go
Labels: lgtm, size/XS, approved, cncf-cla: yes, lifecycle/stale, ok-to-test

#4162 [feat:gw-api] add support for capacity reservation
  apis/gateway/v1beta1/loadbalancerconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  controllers/gateway/gateway_controller.go
  pkg/gateway/model/model_build_loadbalancer.go
  pkg/gateway/model/model_build_loadbalancer_test.go
Labels: lgtm, size/L, cncf-cla: yes, ok-to-test

#3945 chore(doc): update service healthcheck timeout documentation
  docs/guide/service/annotations.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, ok-to-test

#4169 Bump version to 2.13
  Makefile
  config/controller/kustomization.yaml
  config/rbac/role.yaml
  controllers/gateway/gateway_controller.go
  docs/deploy/installation.md
  docs/examples/echo_server.md
  docs/guide/gateway/assets/gateway-full.png
  docs/guide/gateway/gateway.md
  docs/guide/gateway/loadbalancerconfig.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/templates/rbac.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/XL

#4174 [feat gw-api] add hostname handling logic
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/utilities.go
  pkg/gateway/model/utilities_test.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/mock_route.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/XL

#4177 [bug fix] HandleReconcileError not detecting wrapped errors
  pkg/runtime/reconcile.go
  pkg/runtime/reconcile_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#4178 cut v2.13.1 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M

#4182 [bug fix] fix tls protocol not being detected when generating SG rules
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#4185 cut v2.12.2 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: lgtm, approved, cncf-cla: yes, size/M

#4187 Fix prefixListIDs typos
  docs/guide/ingress/ingress_class.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/S

#4191 [feat gw api] add support for infra labels + annotations
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_manager_test.go
  pkg/model/elbv2/load_balancer.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#4192 [feat: gw api] support gw deletion
  controllers/gateway/gateway_controller.go
  controllers/gateway/utils.go
  controllers/gateway/utils_test.go
  pkg/k8s/events.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4196 Add EKS Auto Mode considerations to documentation
  docs/guide/ingress/annotations.md
  docs/guide/ingress/ingress_class.md
  docs/guide/service/annotations.md
  docs/guide/targetgroupbinding/spec.md
  docs/guide/targetgroupbinding/targetgroupbinding.md
Labels: lgtm, needs-ok-to-test, approved, cncf-cla: yes, size/S

#4195 docs: Change AWS Cognito Domain tip to warning
  docs/guide/ingress/annotations.md
Labels: lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#4190 [feat gw-api] add route status update
  controllers/gateway/gateway_class_controller.go
  controllers/gateway/gateway_controller.go
  controllers/gateway/route_reconciler.go
  controllers/gateway/route_reconciler_test.go
  main.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/listener_attachment_helper_test.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/mock_route_reconciler.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/route_listener_mapper_test.go
  pkg/gateway/routeutils/route_reconciler_utils.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, ok-to-test

#4189 [feat gw api] Implement Gateway Status + Some bug fixes for Gateway
  controllers/gateway/config_resolver.go
  controllers/gateway/gateway_controller.go
  controllers/gateway/utils.go
  controllers/gateway/utils_test.go
  pkg/deploy/elbv2/load_balancer_manager.go
  pkg/deploy/elbv2/load_balancer_manager_test.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/http.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/loader_error.go
  pkg/gateway/routeutils/namespace_selector.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/tcp.go
  pkg/gateway/routeutils/tls.go
  pkg/gateway/routeutils/udp.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
  pkg/model/elbv2/load_balancer.go
  pkg/testutils/client_test_utils.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4206 [feat gw-api]bugfix and prevent backward generation route status update
  controllers/gateway/eventhandlers/grpc_route_events.go
  controllers/gateway/eventhandlers/http_route_events.go
  controllers/gateway/eventhandlers/tcp_route_events.go
  controllers/gateway/eventhandlers/tls_route_events.go
  controllers/gateway/eventhandlers/udp_route_events.go
  controllers/gateway/eventhandlers/utils.go
  controllers/gateway/eventhandlers/utils_test.go
  controllers/gateway/route_reconciler.go
  pkg/gateway/routeutils/descriptor.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/http.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/mock_route.go
  pkg/gateway/routeutils/route_reconciler_utils.go
  pkg/gateway/routeutils/tcp.go
  pkg/gateway/routeutils/tls.go
  pkg/gateway/routeutils/udp.go
  pkg/gateway/routeutils/utils_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4210 [feat gw-api]handle resolvedRef for route status update and update ho…
  apis/gateway/v1beta1/targetgroupconfig_types.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  controllers/gateway/gateway_controller.go
  controllers/gateway/route_reconciler_test.go
  pkg/gateway/model/utilities.go
  pkg/gateway/model/utilities_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/loader_error.go
  pkg/gateway/routeutils/namespace_selector.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test
