Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-02, with the labels that each got.

#4062 change pod mutator webhook to fail-open
  helm/aws-load-balancer-controller/templates/webhook.yaml
  webhooks/core/pod_mutator.go
Labels: lgtm, size/XS, approved, cncf-cla: yes

#4063 add toggle to adjust failurePolicy of pod webhook and documentations
  config/webhook/manifests.yaml
  docs/deploy/pod_readiness_gate.md
  helm/aws-load-balancer-controller/templates/webhook.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
Labels: approved, cncf-cla: yes, size/S

#4059 Do not render `.spec.replicas` if Autoscaling is Enabled
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/templates/deployment.yaml
Labels: lgtm, needs-ok-to-test, size/XS, approved, cncf-cla: yes

#4058 Update docs for supporting removal of availability zone for NLB
  .go-version
  docs/guide/service/annotations.md
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#4069 bump go version to 1.23.6 for clean vuln report
  .go-version
  go.mod
Labels: lgtm, size/XS, approved, cncf-cla: yes

#4070 Fix TGB webhook error message to report changes to immutable field
  webhooks/elbv2/targetgroupbinding_validator.go
  webhooks/elbv2/targetgroupbinding_validator_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test
