Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-06, with the labels that each got.

#4214 [feat: gw api] Fix the auto cert discovery logic for secure listeners on gateways
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_listener_test.go
Labels: approved, size/L, cncf-cla: yes

#4193 docs: update security_groups.md tabulation
  docs/deploy/security_groups.md
Labels: cncf-cla: yes, size/S

#4198 [feat: gw api][bug fix] generate sg rules using listener protocols
  controllers/gateway/eventhandlers/gateway_class_events.go
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_security_group.go
  pkg/gateway/model/model_build_security_group_test.go
Labels: approved, size/L, cncf-cla: yes

#4208 Reduce duplicated DescribeTargetGroups calls
  pkg/deploy/elbv2/frontend_nlb_target_synthesizer.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/stack_deployer.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#4220 [gw api] Add TG config logic to find and create user specified TG config.
  apis/gateway/v1beta1/targetgroupconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  controllers/gateway/config_resolver.go
  pkg/gateway/attribute_merger.go
  pkg/gateway/lb_config_merger.go
  pkg/gateway/lb_config_merger_test.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/tag_merger.go
  pkg/gateway/tg_config_constructor.go
  pkg/gateway/tg_config_constructor_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4217 [feat gw-api]implement finalizer
  controllers/gateway/eventhandlers/gateway_events.go
  controllers/gateway/eventhandlers/service_events.go
  controllers/gateway/eventhandlers/utils.go
  controllers/gateway/gateway_controller.go
  controllers/gateway/utils.go
  controllers/gateway/utils_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/k8s/events.go
  pkg/shared_constants/finalizers.go
Labels: needs-ok-to-test, cncf-cla: yes, size/XL

#4221 Add ingress class example
  docs/guide/ingress/ingress_class.md
Labels: approved, cncf-cla: yes, size/M

#4231 Update to go 1.24.4
  .go-version
  go.mod
Labels: lgtm, size/XS, approved, cncf-cla: yes

#4230 tg / lb conf finalizers
  controllers/gateway/eventhandlers/gateway_class_events.go
  controllers/gateway/eventhandlers/gatewayclass/load_balancer_configuration_events.go
  controllers/gateway/eventhandlers/load_balancer_configuration_events.go
  controllers/gateway/eventhandlers/service_events.go
  controllers/gateway/gateway_class_controller.go
  controllers/gateway/gateway_controller.go
  controllers/gateway/loadbalancer_configuration_controller.go
  controllers/gateway/targetgroup_configuration_controller.go
  controllers/gateway/utils.go
  main.go
  pkg/gateway/constants/controller_constants.go
  pkg/gateway/gatewayutils/gateway_utils.go
  pkg/gateway/gatewayutils/gateway_utils_test.go
  pkg/gateway/gatewayutils/lb_config_utils.go
  pkg/gateway/gatewayutils/lb_config_utils_test.go
  pkg/gateway/referencecounter/service_reference_counter.go
  pkg/gateway/referencecounter/service_reference_counter_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/tg_config_utils.go
  pkg/shared_constants/finalizers.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4234 cut v2.13.3 release
  Makefile
  config/controller/kustomization.yaml
  docs/deploy/installation.md
  docs/examples/echo_server.md
  helm/aws-load-balancer-controller/Chart.yaml
  helm/aws-load-balancer-controller/test.yaml
  helm/aws-load-balancer-controller/values.yaml
  version-stable.txt
  version.txt
Labels: approved, cncf-cla: yes, size/M

#4093 Feat(performance): Use protobuf as default type instead of json
  pkg/config/runtime_config.go
Labels: lgtm, size/XS, cncf-cla: yes, ok-to-test

#4244 update ci k8s version
  scripts/ci_e2e_test.sh
Labels: lgtm, size/XS, approved, cncf-cla: yes

#4243 clear confusion around using ClusterIP service and Instance targets
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/ingress/model_build_target_group.go
  pkg/service/model_build_target_group.go
Labels: lgtm, approved, cncf-cla: yes, size/M
