Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-08, with the labels that each got.

#4288 [feat gw-api]implement hostname uniqueness for httproute and grpcrout…
  go.mod
  go.sum
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/listener_attachment_helper_test.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/route_listener_mapper_test.go
  test/e2e/service/nlb_instance_target_test.go
  test/e2e/service/nlb_ip_target_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4277 [Gateway API] Add Addon Support
  .gitignore
  apis/gateway/v1beta1/loadbalancerconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_listenerruleconfigurations.yaml
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  controllers/gateway/addons.go
  controllers/gateway/addons_test.go
  controllers/gateway/gateway_controller.go
  helm/aws-load-balancer-controller/crds/gateway-crds.yaml
  pkg/addon/addon.go
  pkg/gateway/constants/controller_constants.go
  pkg/gateway/lb_config_merger.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/model_build_addon.go
  pkg/gateway/model/model_build_addon_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4281 feat: allow targetGroupName instead of targetGroupARN in forward action ingress annotations
  docs/guide/ingress/annotations.md
  pkg/ingress/config_types.go
  pkg/ingress/enhanced_backend_builder.go
  pkg/ingress/enhanced_backend_builder_test.go
  pkg/ingress/model_build_actions.go
  pkg/ingress/model_build_actions_test.go
  pkg/ingress/model_builder.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4293 modify PrefixListsIDs with backward compatibility
  apis/elbv2/v1beta1/ingressclassparams_types.go
  apis/elbv2/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_listener.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4290 feature: add load balancer name to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_load_balancer.go
  pkg/ingress/model_build_load_balancer_test.go
Labels: lgtm, cncf-cla: yes, size/M, ok-to-test

#4299 upgrade go version
  .go-version
  go.mod
  go.sum
Labels: lgtm, size/XS, approved, cncf-cla: yes

#4298 [feat:gw api] Add tg stickiness and fixed response
  apis/gateway/v1beta1/listenerruleconfig_types.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_listenerruleconfigurations.yaml
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  config/crd/gateway/kustomization.yaml
  helm/aws-load-balancer-controller/crds/gateway-crds.yaml
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_listener_test.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/routeutils/descriptor.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/grpc_test.go
  pkg/gateway/routeutils/http.go
  pkg/gateway/routeutils/http_test.go
  pkg/gateway/routeutils/listener_rule_config_utils.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/mock_route.go
  pkg/gateway/routeutils/route_rule.go
  pkg/gateway/routeutils/route_rule_action.go
  pkg/gateway/routeutils/route_rule_action_test.go
  pkg/gateway/routeutils/route_rule_condition.go
  pkg/gateway/routeutils/route_rule_condition_test.go
  pkg/gateway/routeutils/tcp.go
  pkg/gateway/routeutils/tcp_test.go
  pkg/gateway/routeutils/tls.go
  pkg/gateway/routeutils/tls_test.go
  pkg/gateway/routeutils/udp.go
  pkg/gateway/routeutils/udp_test.go
  pkg/gateway/routeutils/utils_test.go
Labels: lgtm, size/XXL, cncf-cla: yes

#4295 add granular NLBSG disable annotation
  docs/deploy/configurations.md
  docs/guide/service/annotations.md
  go.mod
  go.sum
  pkg/annotations/constants.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#4219 fix/docs: formatting issue in security_groups.md
  docs/deploy/security_groups.md
Labels: size/XS, cncf-cla: yes

#4201 Fix IngressClassParams CRD singular naming to resolve SingularConflict
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
Labels: lgtm, size/XS, cncf-cla: yes, ok-to-test

#3961 Add `wafv2AclArn` field to IngressClassParams
  apis/elbv2/v1beta1/ingressclassparams_types.go
  config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
  docs/guide/ingress/ingress_class.md
  helm/aws-load-balancer-controller/crds/crds.yaml
  pkg/ingress/model_build_load_balancer_addons.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#3581 feat: add target group info metric
  controllers/gateway/gateway_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/guide/metrics/prometheus/index.md
  main.go
  pkg/deploy/elbv2/target_group_binding_manager.go
  pkg/deploy/elbv2/target_group_binding_manager_test.go
  pkg/deploy/stack_deployer.go
  pkg/metrics/aws/target_group.go
Labels: size/L, cncf-cla: yes, ok-to-test

#4311 add configurable timeout for dns propagation
  docs/examples/grpc_server.md
  go.mod
  go.sum
  main.go
  pkg/aws/cloud.go
  pkg/aws/services/elbv2.go
  test/e2e/ingress/vanilla_ingress_test.go
  test/framework/framework.go
  test/framework/options.go
  test/framework/utils/poll.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash

#4316 fix http / grpc route rule generation
  config/rbac/role.yaml
  controllers/gateway/eventhandlers/grpc_route_events.go
  controllers/gateway/eventhandlers/listener_rule_configuration_events.go
  controllers/gateway/eventhandlers/reference_grant_events.go
  controllers/gateway/eventhandlers/service_events.go
  controllers/gateway/gateway_controller.go
  controllers/gateway/route_reconciler.go
  controllers/gateway/utils_test.go
  docs/guide/gateway/gateway.md
  pkg/gateway/constants/controller_constants.go
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/gateway/routeutils/constants.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/grpc_test.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/listener_attachment_helper_test.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/route_listener_mapper_test.go
  pkg/gateway/routeutils/route_rule_action.go
  pkg/gateway/routeutils/route_rule_condition.go
  pkg/gateway/routeutils/route_rule_condition_test.go
  pkg/gateway/routeutils/route_rule_precedence.go
  pkg/gateway/routeutils/route_rule_precedence_test.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
Labels: approved, size/XXL, cncf-cla: yes

#4321 [feat gw-api]support multiple header value in condition
  pkg/gateway/routeutils/route_rule_condition.go
  pkg/gateway/routeutils/route_rule_condition_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes

#4323 [gw api] add grpc e2e tests
  test/e2e/gateway/alb_instance_target_test.go
  test/e2e/gateway/alb_ip_target_test.go
  test/e2e/gateway/alb_resource_stack.go
  test/e2e/gateway/alb_test_helper.go
  test/e2e/gateway/consts.go
  test/e2e/gateway/grpc/echo/echo.pb.go
  test/e2e/gateway/grpc/echo/echo_grpc.pb.go
  test/e2e/gateway/shared_resource_definitions.go
  test/framework/utils/constants.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes
