Repository kubernetes-sigs/aws-load-balancer-controller, pull requests merged in 2025-04, with the labels that each got.

#4096 [feat:gwapi] Add context-aware TargetGroupConfiguration and LoadBalancerConfiguration CRDs for Gateway API
  Makefile
  apis/gateway/v1beta1/groupversion_info.go
  apis/gateway/v1beta1/loadbalancerconfig_types.go
  apis/gateway/v1beta1/targetgroupconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  config/crd/gateway/kustomization.yaml
Labels: approved, size/XXL, cncf-cla: yes

#4125 [feat GW API] Add initial reconciler + grant enforcement
  .go-version
  config/rbac/role.yaml
  controllers/gateway/constants.go
  controllers/gateway/gateway_controller.go
  go.mod
  main.go
  pkg/config/controller_config.go
  pkg/config/feature_gates.go
  pkg/gateway/model/model_builder.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/namespace_selector.go
  pkg/gateway/routeutils/route_attachment_helper.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/test_utils.go
  pkg/metrics/util/reconcile_counter.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4134 chore: change tgb field to lowercase everywhere to avoid logs dropped…
  controllers/elbv2/targetgroupbinding_deferred_reconciler.go
Labels: lgtm, cncf-cla: yes, size/S, ok-to-test

#4145 support cli flag to enable manage backend SG rules for ALB
  config/webhook/manifests.yaml
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/deploy/configurations.md
  docs/deploy/security_groups.md
  go.mod
  go.sum
  helm/aws-load-balancer-controller/README.md
  helm/aws-load-balancer-controller/templates/deployment.yaml
  helm/aws-load-balancer-controller/values.yaml
  pkg/config/controller_config.go
  pkg/config/controller_config_test.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/service/model_build_load_balancer.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_builder.go
  pkg/service/model_builder_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, ok-to-test

#4120 Docs: Custom Shared Backend Security Groups
  docs/deploy/security_groups.md
Labels: lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#4119 Docs: clarify controller configuration and helm options
  docs/deploy/configurations.md
Labels: lgtm, needs-ok-to-test, size/XS, cncf-cla: yes

#4137 Subnet Discovery for Gateway API
  apis/gateway/v1beta1/loadbalancerconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  config/webhook/manifests.yaml
  controllers/gateway/gateway_controller.go
  go.mod
  go.sum
  main.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/constants.go
  pkg/gateway/model/model_build_loadbalancer.go
  pkg/gateway/model/model_build_subnet.go
  pkg/gateway/model/model_build_subnet_test.go
  pkg/gateway/model/model_builder.go
  pkg/gateway/model/subnet/eip_mutator.go
  pkg/gateway/model/subnet/eip_mutator_test.go
  pkg/gateway/model/subnet/ipv6_mutator.go
  pkg/gateway/model/subnet/ipv6_mutator_test.go
  pkg/gateway/model/subnet/mutator.go
  pkg/gateway/model/subnet/private_ipv4_mutator.go
  pkg/gateway/model/subnet/private_ipv4_mutator_test.go
  pkg/gateway/model/subnet/source_nat_mutator.go
  pkg/gateway/model/subnet/source_nat_mutator_test.go
  pkg/networking/utils.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4148 [feat: gw api] Add eventhandlers for all the gateway resources
  config/rbac/role.yaml
  controllers/gateway/eventhandlers/gateway_class_events.go
  controllers/gateway/eventhandlers/grpc_route_events.go
  controllers/gateway/eventhandlers/http_route_events.go
  controllers/gateway/eventhandlers/load_balancer_configuration_events.go
  controllers/gateway/eventhandlers/service_events.go
  controllers/gateway/eventhandlers/target_group_configuration_events.go
  controllers/gateway/eventhandlers/tcp_route_events.go
  controllers/gateway/eventhandlers/tls_route_events.go
  controllers/gateway/eventhandlers/udp_route_events.go
  controllers/gateway/eventhandlers/utils.go
  controllers/gateway/eventhandlers/utils_test.go
  controllers/gateway/gateway_controller.go
  main.go
  pkg/config/controller_config.go
  pkg/gateway/constants/controller_constants.go
  pkg/gateway/routeutils/backend_test.go
  pkg/gateway/routeutils/descriptor.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/grpc_test.go
  pkg/gateway/routeutils/http.go
  pkg/gateway/routeutils/http_test.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/namespace_selector_test.go
  pkg/gateway/routeutils/tcp.go
  pkg/gateway/routeutils/tcp_test.go
  pkg/gateway/routeutils/test_utils.go
  pkg/gateway/routeutils/tls.go
  pkg/gateway/routeutils/tls_test.go
  pkg/gateway/routeutils/udp.go
  pkg/gateway/routeutils/udp_test.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
  pkg/metrics/util/reconcile_counter.go
  pkg/testutils/client_test_utils.go
Labels: approved, size/XXL, cncf-cla: yes

#4126 Enable frontend NLB
  controllers/gateway/gateway_controller.go
  controllers/ingress/group_controller.go
  controllers/service/service_controller.go
  docs/guide/ingress/annotations.md
  pkg/annotations/constants.go
  pkg/deploy/elbv2/frontend_nlb_target_synthesizer.go
  pkg/deploy/elbv2/frontend_nlb_targets_manager.go
  pkg/deploy/elbv2/target_group_synthesizer.go
  pkg/deploy/stack_deployer.go
  pkg/ingress/model_build_frontend_nlb.go
  pkg/ingress/model_build_frontend_nlb_test.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/model/core/frontend_nlb_target_group.go
  pkg/model/elbv2/target_group.go
  test/e2e/ingress/utils.go
  test/e2e/ingress/vanilla_ingress_test.go
Labels: approved, size/XXL, cncf-cla: yes

#4142 [feat: gw api] Security Group discovery and management
  apis/gateway/v1beta1/loadbalancerconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_loadbalancerconfigurations.yaml
  controllers/gateway/gateway_controller.go
  controllers/service/service_controller.go
  main.go
  pkg/config/controller_config.go
  pkg/config/controller_config_test.go
  pkg/deploy/elbv2/load_balancer_synthesizer.go
  pkg/deploy/tracking/provider.go
  pkg/deploy/tracking/provider_test.go
  pkg/gateway/constants/controller_constants.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/constants.go
  pkg/gateway/model/gateway_tag_helper.go
  pkg/gateway/model/mock_gateway_tag_helper.go
  pkg/gateway/model/model_build_loadbalancer.go
  pkg/gateway/model/model_build_security_group.go
  pkg/gateway/model/model_build_security_group_test.go
  pkg/gateway/model/model_build_subnet.go
  pkg/gateway/model/model_build_subnet_test.go
  pkg/gateway/routeutils/mock_route.go
  pkg/ingress/finalizer.go
  pkg/ingress/group_loader.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
  pkg/metrics/util/reconcile_counter.go
  pkg/networking/backend_sg_provider.go
  pkg/networking/backend_sg_provider_test.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_build_managed_sg.go
  pkg/service/model_builder.go
  pkg/shared_constants/attributes.go
  pkg/shared_constants/finalizers.go
  pkg/shared_constants/icmp.go
  pkg/shared_constants/tag_keys.go
Labels: approved, size/XXL, cncf-cla: yes

#4149 [feat: gw api] Add eventhandler for the gateway resource
  controllers/gateway/eventhandlers/gateway_events.go
  controllers/gateway/gateway_controller.go
Labels: approved, cncf-cla: yes, size/M

#4113 Allow specifying the same certificate for both default and SNI
  docs/guide/ingress/annotations.md
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test, tide/merge-method-merge

#4150 [feat: gw-api] Creating Target Group + TGB from Gateway spec
  apis/gateway/v1beta1/targetgroupconfig_types.go
  apis/gateway/v1beta1/zz_generated.deepcopy.go
  config/crd/gateway/gateway-crds.yaml
  config/crd/gateway/gateway.k8s.aws_targetgroupconfigurations.yaml
  controllers/gateway/gateway_controller.go
  main.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/model_build_security_group.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/gateway/model/utilities.go
  pkg/gateway/routeutils/backend.go
  pkg/gateway/routeutils/constants.go
  pkg/gateway/routeutils/descriptor.go
  pkg/gateway/routeutils/grpc.go
  pkg/gateway/routeutils/grpc_test.go
  pkg/gateway/routeutils/http.go
  pkg/gateway/routeutils/http_test.go
  pkg/gateway/routeutils/listener_attachment_helper.go
  pkg/gateway/routeutils/listener_attachment_helper_test.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/loader_test.go
  pkg/gateway/routeutils/mock_route.go
  pkg/gateway/routeutils/route_attachment_helper.go
  pkg/gateway/routeutils/route_attachment_helper_test.go
  pkg/gateway/routeutils/route_listener_mapper.go
  pkg/gateway/routeutils/route_listener_mapper_test.go
  pkg/gateway/routeutils/tcp.go
  pkg/gateway/routeutils/tcp_test.go
  pkg/gateway/routeutils/tls.go
  pkg/gateway/routeutils/tls_test.go
  pkg/gateway/routeutils/udp.go
  pkg/gateway/routeutils/udp_test.go
  pkg/gateway/routeutils/utils.go
  pkg/gateway/routeutils/utils_test.go
  pkg/ingress/model_build_frontend_nlb.go
  pkg/ingress/model_build_target_group.go
  pkg/service/model_build_load_balancer_test.go
  pkg/service/model_build_target_group.go
  pkg/service/model_build_target_group_test.go
  pkg/service/model_builder.go
  pkg/shared_constants/attributes.go
  pkg/shared_constants/healthcheck.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes, tide/merge-method-squash

#4152 [feat gw api] Add unit tests and some refactoring to TG logic
  apis/gateway/v1beta1/targetgroupconfig_types.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4156 [feat:gw-api] add support for ServiceExternalTrafficPolicyLocal
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, ok-to-test

#4160 [feat: gw api] Add common listener config for gateway api
  controllers/gateway/gateway_controller.go
  pkg/deploy/elbv2/listener_synthesizer.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_listener_test.go
  pkg/gateway/model/model_build_security_group.go
  pkg/gateway/model/model_build_security_group_test.go
  pkg/gateway/model/model_build_target_group.go
  pkg/gateway/model/model_build_target_group_test.go
  pkg/gateway/routeutils/loader.go
  pkg/gateway/routeutils/loader_test.go
Labels: lgtm, approved, size/XXL, cncf-cla: yes

#4159 Add cert discovery
  controllers/gateway/gateway_controller.go
  pkg/certs/cert_discovery.go
  pkg/certs/cert_discovery_mocks.go
  pkg/certs/cert_discovery_test.go
  pkg/gateway/model/base_model_builder.go
  pkg/gateway/model/model_build_listener.go
  pkg/gateway/model/model_build_listener_test.go
  pkg/ingress/model_builder.go
  pkg/ingress/model_builder_test.go
Labels: lgtm, approved, size/L, cncf-cla: yes, tide/merge-method-squash
